workflows:
  ios_release:
    name: FireOpsCalc iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: 16.4
      cocoapods: default
      node: 20.11.1

      vars:
        # --- App identity ---
        PRODUCT_BUNDLE_IDENTIFIER: "com.fireopscalc.app"
        DEVELOPMENT_TEAM: "QZ55W58398"

        # --- Xcode project paths ---
        WORKSPACE: "ios/App/App.xcworkspace"
        FALLBACK_SCHEME: "App"

        # --- Archive/Export output paths ---
        ARCHIVE_PATH: "/Users/builder/clone/Export/App.xcarchive"
        EXPORT_DIR: "/Users/builder/clone/Export"
        IPA_NAME: "FireOpsCalc.ipa"

        # --- Codemagic signing asset reference names (must match Team → Code signing) ---
        CM_DISTRIBUTION_CERT_REF: "FireOpsCalc_Distribution_2025"
        CM_APPSTORE_PROFILE_REF: "FireOpsCalc_AppStore_Profile"

    ios_signing:
      certificates:
        - $CM_DISTRIBUTION_CERT_REF
      provisioning_profiles:
        - $CM_APPSTORE_PROFILE_REF

    scripts:
      - name: Show Xcode version
        script: xcodebuild -version

      - name: Install JS deps & sync iOS
        script: |
          set -e
          npm ci || npm i
          npx cap sync ios

      - name: Install CocoaPods (if Podfile exists)
        script: |
          set -e
          if [ -f "ios/App/Podfile" ]; then
            cd ios/App
            pod repo update
            pod install
            cd ../..
          else
            echo "No Podfile found — skipping pod install."
          fi

      - name: Detect shared scheme (no Python)
        script: |
          set -e
          echo "Available schemes in $WORKSPACE:"
          xcodebuild -list -workspace "$WORKSPACE" 2>/dev/null || true

          # Pull scheme list using awk (lines under 'Schemes:' until blank line)
          SCHEME_DETECTED="$(xcodebuild -list -workspace "$WORKSPACE" 2>/dev/null \
            | awk '/Schemes:/ {flag=1; next} /^$/ {flag=0} flag' \
            | sed 's/^[[:space:]]*//' \
            | head -n1)"

          # Prefer 'App' if it exists
          if xcodebuild -list -workspace "$WORKSPACE" 2>/dev/null | grep -qE '^[[:space:]]*App$'; then
            SCHEME_DETECTED="App"
          fi

          # Fallback if still empty
          if [ -z "$SCHEME_DETECTED" ]; then
            SCHEME_DETECTED="$FALLBACK_SCHEME"
          fi

          echo "Using scheme: $SCHEME_DETECTED"
          echo "SCHEME_DETECTED=$SCHEME_DETECTED" >> "$CM_ENV"

      - name: Verify signing files present
        script: |
          set -e
          echo "Listing installed provisioning profiles:"
          ls -lah "$HOME/Library/MobileDevice/Provisioning Profiles" || true
          echo "Search for com.fireopscalc.app in profiles:"
          grep -R "com.fireopscalc.app" "$HOME/Library/MobileDevice/Provisioning Profiles" -n || true

      - name: Build Xcode archive (sign only App target)
        script: |
          set -e
          mkdir -p "$EXPORT_DIR"
          xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME_DETECTED" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            -destination 'generic/platform=iOS' \
            clean archive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$PRODUCT_BUNDLE_IDENTIFIER" \
            CODE_SIGN_IDENTITY= \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER= \
            \
            "CODE_SIGN_IDENTITY[project=App][target=App]=Apple Distribution" \
            "PROVISIONING_PROFILE_SPECIFIER[project=App][target=App]=$CM_APPSTORE_PROFILE_REF" \
            \
            "CODE_SIGNING_ALLOWED[project=Pods]=NO" \
            "CODE_SIGNING_ALLOWED[project=Pods][target=Pods-App]=NO" \
            "CODE_SIGNING_ALLOWED[project=Pods][target=Capacitor]=NO" \
            "CODE_SIGNING_ALLOWED[project=Pods][target=CapacitorCordova]=NO"

      - name: Create exportOptions.plist
        script: |
          set -e
          cat > "$EXPORT_DIR/ExportOptions.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>method</key><string>app-store</string>
  <key>signingStyle</key><string>manual</string>
  <key>teamID</key><string>${DEVELOPMENT_TEAM}</string>
  <key>provisioningProfiles</key>
  <dict>
    <key>${PRODUCT_BUNDLE_IDENTIFIER}</key><string>${CM_APPSTORE_PROFILE_REF}</string>
  </dict>
  <key>compileBitcode</key><false/>
  <key>destination</key><string>export</string>
</dict>
</plist>
EOF

      - name: Export IPA
        script: |
          set -e
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist "$EXPORT_DIR/ExportOptions.plist" \
            -exportPath "$EXPORT_DIR"

          # Normalize IPA name for artifacts
          if [ -f "$EXPORT_DIR/$SCHEME_DETECTED.ipa" ]; then
            mv "$EXPORT_DIR/$SCHEME_DETECTED.ipa" "$EXPORT_DIR/$IPA_NAME"
          elif [ -f "$EXPORT_DIR/App.ipa" ]; then
            mv "$EXPORT_DIR/App.ipa" "$EXPORT_DIR/$IPA_NAME"
          fi

          echo "Contents of export dir:"
          ls -lah "$EXPORT_DIR"
          if [ ! -f "$EXPORT_DIR/$IPA_NAME" ]; then
            echo "ERROR: IPA not found after export."
            exit 1
          fi
          echo "APP_IPA_PATH=$EXPORT_DIR/$IPA_NAME" >> "$CM_ENV"

    artifacts:
      - Export/*.ipa
      - Export/*.xcarchive
      - Export/ExportOptions.plist
