workflows:
  ios_release:
    name: iOS Release (App Store / TestFlight)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: 16.4
      cocoapods: default
      node: 20
      groups:
        - ios-signing
      vars:
        BUNDLE_ID: com.fireopscalc.app
        IOS_SCHEME: App
        IOS_WORKSPACE: ios/App/App.xcworkspace
        DEVELOPMENT_TEAM: $APP_STORE_CONNECT_TEAM_ID

    scripts:
      - name: Show tool versions
        script: |
          node -v
          npm -v
          pod --version
          xcodebuild -version

      - name: Install dependencies
        script: npm ci

      - name: Build web assets
        script: |
          if npm run | grep -qE '^[[:space:]]+build($|:)'; then
            npm run build || true
          else
            echo "No build script, skipping."
          fi

      - name: Sync Capacitor iOS
        script: npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod repo update
          pod install --verbose

      - name: Build iOS archive (Release)
        script: |
          xcodebuild -workspace "$IOS_WORKSPACE" \
            -scheme "$IOS_SCHEME" \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath "$CM_BUILD_DIR/App" \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            clean archive | xcpretty

      - name: Export IPA for App Store
        script: |
          cat > ExportOptions.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>automatic</string>
            <key>teamID</key><string>${DEVELOPMENT_TEAM}</string>
          </dict>
          </plist>
          PLIST
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportPath "$CM_BUILD_DIR/Export" \
            -exportOptionsPlist ExportOptions.plist | xcpretty

    artifacts:
      - $CM_BUILD_DIR/Export/*.ipa
      - $CM_BUILD_DIR/ArchiveResult.xcresult
      - ios/App/build/**/*.dSYM

    publishing:
      app_store_connect:
        auth: api_key
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        private_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
