workflows:
  ios-capacitor:
    name: iOS Capacitor → TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      node: 20            # <-- fix: your deps want Node >=20
      xcode: latest
      cocoapods: default
      vars:
        # ✅ change these 2 to match your app
        APP_IDENTIFIER: com.fireopscalc.app
        APP_NAME: FireOps Calc

        # ✅ map to your Codemagic env vars (make sure they exist in Settings → Environment variables)
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY   # Key ID (10 chars)
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSU      # Issuer ID (UUID)
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIV    # .p8 contents (BEGIN/END included)

    scripts:
      - name: Install dependencies and sync Capacitor
        script: |
          set -e
          echo "🔧 Node version:" && node -v
          echo "📦 Trying npm ci..."
          if ! npm ci; then
            echo "⚠️ npm ci failed, retrying with npm install --legacy-peer-deps"
            npm install --legacy-peer-deps
          fi
          echo "🔗 npx cap sync ios"
          npx cap sync ios

      - name: Install CocoaPods (if present)
        script: |
          if [ -f "ios/App/Podfile" ]; then
            echo "📦 pod install"
            cd ios/App
            pod install
            cd ../../
          else
            echo "ℹ️ No Podfile found, skipping pods"
          fi

      - name: Automatic code signing (App Store Connect API)
        script: |
          xcode-project use-profiles \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"

      - name: Build .ipa
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App" \
            --archive-path "$CM_BUILD_DIR/App.xcarchive"

      - name: Publish to TestFlight
        script: |
          IPA_PATH="$(find . -type f -name '*.ipa' | head -n 1)"
          echo "📤 Uploading $IPA_PATH to TestFlight"
          app-store-connect publish \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --path "$IPA_PATH" \
            --submit-to-testflight

    artifacts:
      - "**/*.ipa"
      - "ios/App/build/**"
