workflows:
  ios_release:
    name: FireOpsCalc iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: 16.4
      cocoapods: default
      node: 20.11.1

      vars:
        # --- App identity ---
        PRODUCT_BUNDLE_IDENTIFIER: "com.fireopscalc.app"
        DEVELOPMENT_TEAM: "QZ55W58398"

        # --- Xcode project paths ---
        WORKSPACE: "ios/App/App.xcworkspace"
        SCHEME: "App"   # set explicitly; change if your shared scheme has a different name

        # --- Archive/Export output paths ---
        ARCHIVE_PATH: "/Users/builder/clone/Export/App.xcarchive"
        EXPORT_DIR: "/Users/builder/clone/Export"
        IPA_NAME: "FireOpsCalc.ipa"

        # --- Codemagic signing asset reference names (must match Team → Code signing) ---
        CM_DISTRIBUTION_CERT_REF: "FireOpsCalc_Distribution_2025"
        CM_APPSTORE_PROFILE_REF: "FireOpsCalc_AppStore_Profile"

    ios_signing:
      certificates:
        - $CM_DISTRIBUTION_CERT_REF
      provisioning_profiles:
        - $CM_APPSTORE_PROFILE_REF

    scripts:
      - name: Show Xcode version
        script: |
          set -e
          xcodebuild -version

      - name: Install JS deps & sync iOS
        script: |
          set -e
          npm ci || npm i
          npx cap sync ios

      - name: Install CocoaPods (if Podfile exists)
        script: |
          set -e
          if [ -f "ios/App/Podfile" ]; then
            cd ios/App
            pod repo update
            pod install
            cd ../..
          else
            echo "No Podfile found — skipping pod install."
          fi

      - name: Verify signing files present
        script: |
          set -e
          echo "Provisioning profiles installed:"
          ls -lah "$HOME/Library/MobileDevice/Provisioning Profiles" || true
          echo "Looking for com.fireopscalc.app in profiles:"
          grep -R "com.fireopscalc.app" "$HOME/Library/MobileDevice/Provisioning Profiles" -n || true

      - name: Build Xcode archive (sign only App target)
        script: |
          set -e
          mkdir -p "$EXPORT_DIR"
          xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            -destination 'generic/platform=iOS' \
            clean archive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$PRODUCT_BUNDLE_IDENTIFIER" \
            CODE_SIGN_IDENTITY= \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER= \
            \
            "CODE_SIGN_IDENTITY[project=App][target=App]=Apple Distribution" \
            "PROVISIONING_PROFILE_SPECIFIER[project=App][target=App]=$CM_APPSTORE_PROFILE_REF" \
            \
            "CODE_SIGNING_ALLOWED[project=Pods]=NO" \
            "CODE_SIGNING_ALLOWED[project=Pods][target=Pods-App]=NO" \
            "CODE_SIGNING_ALLOWED[project=Pods][target=Capacitor]=NO" \
            "CODE_SIGNING_ALLOWED[project=Pods][target=CapacitorCordova]=NO"

      - name: Create exportOptions.plist (no XML heredoc)
        script: |
          set -e
          PLIST="$EXPORT_DIR/ExportOptions.plist"
          # Create minimal plist root
          printf '%s' '<?xml version="1.0" encoding="UTF-8"?>' > "$PLIST"
          printf '%s' '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' >> "$PLIST"
          printf '%s' '<plist version="1.0"><dict></dict></plist>' >> "$PLIST"

          # Populate keys via PlistBuddy
          /usr/libexec/PlistBuddy -c "Add :method string app-store" "$PLIST"
          /usr/libexec/PlistBuddy -c "Add :signingStyle string manual" "$PLIST"
          /usr/libexec/PlistBuddy -c "Add :teamID string ${DEVELOPMENT_TEAM}" "$PLIST"
          /usr/libexec/PlistBuddy -c "Add :compileBitcode bool false" "$PLIST"
          /usr/libexec/PlistBuddy -c "Add :destination string export" "$PLIST"
          /usr/libexec/PlistBuddy -c "Add :provisioningProfiles dict" "$PLIST"
          /usr/libexec/PlistBuddy -c "Add :provisioningProfiles:${PRODUCT_BUNDLE_IDENTIFIER} string ${CM_APPSTORE_PROFILE_REF}" "$PLIST"

          echo "exportOptions.plist created:"
          /usr/libexec/PlistBuddy -c "Print" "$PLIST" || true

      - name: Export IPA
        script: |
          set -e
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist "$EXPORT_DIR/ExportOptions.plist" \
            -exportPath "$EXPORT_DIR"

          # Normalize IPA name for artifacts
          if [ -f "$EXPORT_DIR/$SCHEME.ipa" ]; then
            mv "$EXPORT_DIR/$SCHEME.ipa" "$EXPORT_DIR/$IPA_NAME"
          elif [ -f "$EXPORT_DIR/App.ipa" ]; then
            mv "$EXPORT_DIR/App.ipa" "$EXPORT_DIR/$IPA_NAME"
          fi

          echo "Contents of export dir:"
          ls -lah "$EXPORT_DIR"
          if [ ! -f "$EXPORT_DIR/$IPA_NAME" ]; then
            echo "ERROR: IPA not found after export."
            exit 1
          fi
          echo "APP_IPA_PATH=$EXPORT_DIR/$IPA_NAME" >> "$CM_ENV"

    artifacts:
      - Export/*.ipa
      - Export/*.xcarchive
      - Export/ExportOptions.plist
