workflows:
  ios_release:
    name: iOS Release (App Store / TestFlight)
    instance_type: mac_mini_m2

    environment:
      xcode: 16.4
      node: 20
      cocoapods: default
      vars:
        APP_BUNDLE_ID: com.fireopscalc.app
        DEVELOPMENT_TEAM: QZ55W58398
        IOS_SCHEME: App
        IOS_WORKSPACE: ios/App/App.xcworkspace
        IOS_PROJECT: ios/App/App.xcodeproj

    scripts:
      - name: Show tool versions
        script: |
          node -v
          npm -v
          pod --version
          xcodebuild -version

      - name: Install dependencies
        script: |
          npm ci

      - name: Build web assets (try common scripts)
        script: |
          if npm run | grep -qE '^[[:space:]]*build'; then
            npm run build
          else
            echo "No npm build script found; skipping web build"
          fi

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        working_directory: ios/App
        script: |
          pod repo update
          pod install

      # IMPORTANT: keep signing automatic everywhere (App + Pods)
      - name: Build iOS archive (Release) with AUTOMATIC signing
        script: |
          set -e
          ARCHIVE_PATH="$CM_BUILD_DIR/App.xcarchive"
          xcodebuild \
            -workspace "$IOS_WORKSPACE" \
            -scheme "$IOS_SCHEME" \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath "$ARCHIVE_PATH" \
            -allowProvisioningUpdates \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$APP_BUNDLE_ID" \
            clean archive | xcbeautify
          ls -la "$ARCHIVE_PATH"

      - name: Export IPA (App Store)
        script: |
          set -e
          cat > $CM_BUILD_DIR/ExportOptions.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>automatic</string>
            <key>uploadBitcode</key><false/>
            <key>compileBitcode</key><false/>
            <key>destination</key><string>export</string>
          </dict>
          </plist>
          EOF
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/ExportOptions.plist" \
            -exportPath "$CM_BUILD_DIR" | xcbeautify
          echo "Export directory contents:" && ls -la "$CM_BUILD_DIR"

    artifacts:
      - $CM_BUILD_DIR/*.ipa
      - $CM_BUILD_DIR/App.xcarchive
      - $CM_BUILD_DIR/ArchiveResult.xcresult
      - $CM_BUILD_DIR/*.dSYM.zip

    publishing:
      app_store_connect:
        auth: integration        # uses the green “FireOpsCalc_iOS-KEY” you connected
        submit_to_testflight: true
        # optional: send to specific groups
        # beta_groups:
        #   - External Testers
