workflows:
  ios_release:
    name: FireOpsCalc iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60

    # you already have this in UI, we must reference it here
    integrations:
      app_store_connect: FireCalc

    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true

    environment:
      xcode: 16.4
      cocoapods: default
      node: 20.11.1
      vars:
        WORKSPACE: "ios/App/App.xcworkspace"
        SCHEME: "App"
        BUNDLE_ID: "com.fireopscalc.app"
        TEAM_ID: "QZ55W58398"

        ARCHIVE_PATH: "/Users/builder/clone/build/App.xcarchive"
        EXPORT_DIR: "/Users/builder/clone/Export"
        IPA_NAME: "FireOpsCalc.ipa"

    scripts:
      # 0) show what CM mounted BEFORE we start
      - name: 0) Show mounted signing stuff
        script: |
          echo "=== BEFORE FETCH ==="
          echo "CM_PROVISIONING_PROFILES_DIR=$CM_PROVISIONING_PROFILES_DIR"
          if [ -n "$CM_PROVISIONING_PROFILES_DIR" ] && [ -d "$CM_PROVISIONING_PROFILES_DIR" ]; then
            ls -la "$CM_PROVISIONING_PROFILES_DIR" || true
          else
            echo "⚠️ CM_PROVISIONING_PROFILES_DIR is empty right now"
          fi

      # 1) get signing from App Store Connect (using workspace integration), then import
      - name: 1) Fetch signing from ASC and apply
        script: |
          set -e
          echo "=== 1a) ASC fetch (App Store) ==="
          app-store-connect fetch-signing-files com.fireopscalc.app \
            --type IOS_APP_STORE \
            --create \
            || echo "⚠️ ASC fetch app-store failed, will continue"

          echo "=== 1b) ASC fetch (DEV, optional) ==="
          app-store-connect fetch-signing-files com.fireopscalc.app \
            --type IOS_APP_DEVELOPMENT \
            --create \
            || echo "⚠️ ASC fetch dev failed, ok"

          echo "=== 1c) import whatever Codemagic mounted ==="
          keychain add-certificates || echo "⚠️ keychain add-certificates failed"

          echo "=== 1d) apply profiles to Xcode project ==="
          xcode-project use-profiles || echo "⚠️ xcode-project use-profiles failed (usually means no profiles)"

          echo "=== 1e) AFTER FETCH: what profiles do we actually have? ==="
          echo "CM_PROVISIONING_PROFILES_DIR=$CM_PROVISIONING_PROFILES_DIR"
          if [ -n "$CM_PROVISIONING_PROFILES_DIR" ] && [ -d "$CM_PROVISIONING_PROFILES_DIR" ]; then
            ls -R "$CM_PROVISIONING_PROFILES_DIR" || true
          else
            echo "❌ STILL EMPTY — this is why export later says “App.app requires a provisioning profile”"
          fi

      # 2) build web (your normal front / Capacitor)
      - name: 2) Install Node deps & build web
        script: |
          if [ -f package.json ]; then
            if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
              npm ci || npm install
            else
              npm install
            fi
            npm run build --if-present
          else
            echo "No package.json, skipping web build."
          fi

      # 3) Capacitor sync so ios/App/App/public exists
      - name: 3) Capacitor sync iOS
        script: |
          if [ -f capacitor.config.ts ] || [ -f capacitor.config.json ] || [ -f capacitor.config.js ]; then
            npx cap sync ios
          else
            echo "No capacitor config, skipping npx cap sync ios"
          fi
          echo "=== ios/App/App after sync ==="
          ls -la ios/App/App || true

      # 4) pods
      - name: 4) Install CocoaPods
        script: |
          set -e
          cd ios/App
          pod install --repo-update || pod install
          cd ../..

      # 5) make ExportOptions.plist
      - name: 5) Create ExportOptions.plist
        script: |
          set -e
          EXPORT_PLIST="/Users/builder/export_options.plist"
          rm -f "$EXPORT_PLIST"
          /usr/bin/plutil -create xml1 "$EXPORT_PLIST"
          /usr/libexec/PlistBuddy -c "Add :method string app-store" "$EXPORT_PLIST"
          /usr/libexec/PlistBuddy -c "Add :teamID string $TEAM_ID" "$EXPORT_PLIST"
          /usr/libexec/PlistBuddy -c "Add :uploadBitcode bool false" "$EXPORT_PLIST"
          /usr/libexec/PlistBuddy -c "Add :compileBitcode bool false" "$EXPORT_PLIST"
          echo "=== ExportOptions.plist ==="
          /usr/libexec/PlistBuddy -c "Print" "$EXPORT_PLIST"

      # 6) archive (now that use-profiles ran)
      - name: 6) Archive with Xcode (use workspace/scheme)
        script: |
          set -e
          echo "=== xcodebuild archive ==="
          xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath "$ARCHIVE_PATH" \
            archive \
            | xcpretty

          if [ ! -d "$ARCHIVE_PATH" ]; then
            echo "❌ Archive was not created at $ARCHIVE_PATH"
            ls -R /Users/builder/clone/build || true
            exit 1
          fi

      # 7) export
      - name: 7) Export IPA
        script: |
          set -e
          mkdir -p "$EXPORT_DIR"
          echo "=== xcodebuild exportArchive ==="
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist /Users/builder/export_options.plist \
            -exportPath "$EXPORT_DIR" \
            | xcpretty

          IPA_PATH="$(ls -1t "$EXPORT_DIR"/*.ipa 2>/dev/null | head -n 1)"
          if [ -z "$IPA_PATH" ]; then
            echo "❌ No IPA created"
            ls -la "$EXPORT_DIR" || true
            exit 1
          fi

          mv -f "$IPA_PATH" "$EXPORT_DIR/$IPA_NAME"
          echo "✅ IPA at $EXPORT_DIR/$IPA_NAME"

    artifacts:
      - "$EXPORT_DIR/$IPA_NAME"

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
