workflows:
  ios-capacitor:
    name: iOS Capacitor → TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      node: 20
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials   # Must include:
                                  # APP_STORE_CONNECT_KEY_IDENTIFIER
                                  # APP_STORE_CONNECT_ISSUER_ID
                                  # APP_STORE_CONNECT_PRIVATE_KEY
      vars:
        XCODE_SCHEME: App

    scripts:
      - name: Install deps
        script: |
          echo "Node:" && node -v
          npm ci || npm install --legacy-peer-deps

      - name: Build web to dist/
        script: |
          npm run build || true
          if [ ! -f "dist/index.html" ]; then
            mkdir -p dist
            if [ -f "index.html" ]; then
              cp index.html dist/index.html
            else
              echo "dist/index.html missing and no root index.html to copy."
              exit 1
            fi
          fi

      - name: Ensure iOS platform exists & sync
        script: |
          [ -d ios ] || npx cap add ios
          npx cap sync ios

      - name: Detect bundle id from Xcode project
        script: |
          BUNDLE_ID="$(xcode-project detect-bundle-id --workspace 'ios/App/App.xcworkspace' --scheme "$XCODE_SCHEME")"
          if [ -z "$BUNDLE_ID" ]; then
            echo "❌ Could not detect bundle id from Xcode workspace/scheme"
            exit 1
          fi
          echo "✅ Detected bundle id: $BUNDLE_ID"
          echo "BUNDLE_ID=$BUNDLE_ID" >> $CM_ENV

      - name: Debug ASC env (lengths only)
        script: |
          echo "Key ID len: ${#APP_STORE_CONNECT_KEY_IDENTIFIER} (expect ~10)"
          echo "Issuer ID len: ${#APP_STORE_CONNECT_ISSUER_ID} (expect 36)"
          echo "Private key starts with: ${APP_STORE_CONNECT_PRIVATE_KEY:0:27}"

      - name: Fetch signing files (try multiple flag variants)
        script: |
          set -e
          echo "Attempt 1: --identifier"
          if app-store-connect fetch-signing-files \
              --type IOS_APP_STORE \
              --identifier "$BUNDLE_ID" \
              --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
              --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
              --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
              --create; then
            echo "✅ Fetched with --identifier"
          else
            echo "Attempt 2: --app-id"
            if app-store-connect fetch-signing-files \
                --type IOS_APP_STORE \
                --app-id "$BUNDLE_ID" \
                --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
                --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
                --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
                --create; then
              echo "✅ Fetched with --app-id"
            else
              echo "Attempt 3: --bundle-id"
              if app-store-connect fetch-signing-files \
                  --type IOS_APP_STORE \
                  --bundle-id "$BUNDLE_ID" \
                  --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
                  --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
                  --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
                  --create; then
                echo "✅ Fetched with --bundle-id"
              else
                echo "Attempt 4: --app-identifier"
                if app-store-connect fetch-signing-files \
                    --type IOS_APP_STORE \
                    --app-identifier "$BUNDLE_ID" \
                    --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
                    --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
                    --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
                    --create; then
                  echo "✅ Fetched with --app-identifier"
                else
                  echo "❌ All flag variants failed on this runner."
                  echo "CLI help follows:"
                  app-store-connect fetch-signing-files -h || true
                  exit 2
                fi
              fi
            fi
          fi

      - name: Initialize keychain & install certs/profiles
        script: |
          keychain initialize
          keychain add-certificates

      - name: Build .ipa
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "$XCODE_SCHEME"

      - name: Publish to TestFlight
        script: |
          IPA_PATH="$(find . -name '*.ipa' | head -n 1)"
          if [ -z "$IPA_PATH" ]; then
            echo "No .ipa found to upload"; exit 1
          fi
          echo "Uploading $IPA_PATH to TestFlight…"
          app-store-connect publish \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --path "$IPA_PATH" \
            --submit-to-testflight

    artifacts:
      - "**/*.ipa"
      - "ios/App/build/**"
