workflows:
  ios_release:
    name: FireOpsCalc iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60

    # Needed because publishing.auth uses "integration"
    integrations:
      app_store_connect: FireCalc   # exact name from Teams → Integrations

    environment:
      xcode: 16.4
      cocoapods: default
      node: 20.11.1
      vars:
        PRODUCT_BUNDLE_IDENTIFIER: "com.fireopscalc.app"
        DEVELOPMENT_TEAM: "QZ55W58398"
        WORKSPACE: "ios/App/App.xcworkspace"
        SCHEME: "App"                          # <-- hard-coded to avoid detection step
        ARCHIVE_PATH: "/Users/builder/clone/build/App.xcarchive"
        EXPORT_DIR: "/Users/builder/clone/Export"
        EXPORT_PLIST: "/Users/builder/clone/ExportOptions.plist"
        PROVISIONING_PROFILE_SPECIFIER: "FireOpsCalc_AppStore_Profile"
      groups:
        - appstore_connect                     # fine to keep

    cache:
      cache_paths:
        - ~/.npm
        - ~/.cache/CocoaPods
        - ~/Library/Caches/CocoaPods
        - ios/Pods

    scripts:
      - name: Install JS deps & sync iOS
        script: |
          set -e
          npm ci || npm install
          npx cap sync ios

      - name: Ensure CocoaPods are installed
        script: |
          set -e
          cd ios/App
          pod install --repo-update
          cd -

      - name: Import signing assets saved in Codemagic (p12 + mobileprovision)
        script: |
          set -e
          keychain initialize
          # Pulls all certs/profiles you uploaded in Team → Code signing identities
          keychain add-certificates
          security find-identity -v || true

      - name: Create ExportOptions.plist
        script: |
          set -e
          cat > "$EXPORT_PLIST" <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.fireopscalc.app</key>
              <string>FireOpsCalc_AppStore_Profile</string>
            </dict>
            <key>manageAppVersionAndBuildNumber</key><false/>
            <key>stripSwiftSymbols</key><true/>
            <key>uploadSymbols</key><true/>
          </dict>
          </plist>
          PLIST
          /usr/libexec/PlistBuddy -c "Print" "$EXPORT_PLIST" || true

      - name: Build archive (manual signing for App target only)
        script: |
          set -eo pipefail
          if [ -f "$WORKSPACE" ]; then
            WHAT="-workspace $WORKSPACE"
          else
            WHAT="-project ios/App/App.xcodeproj"
          fi

          echo "Building with: $WHAT, scheme: $SCHEME"
          xcodebuild $WHAT \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            -destination "generic/platform=iOS" \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$PRODUCT_BUNDLE_IDENTIFIER" \
            PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_SPECIFIER" \
            "CODE_SIGN_IDENTITY=Apple Distribution" \
            clean archive

          if [ ! -d "$ARCHIVE_PATH" ]; then
            echo "❌ Archive not produced at $ARCHIVE_PATH"
            echo "Dumping list and build settings for debugging:"
            xcodebuild $WHAT -list || true
            xcodebuild $WHAT -scheme "$SCHEME" -showBuildSettings | \
              grep -E 'PRODUCT_NAME|PRODUCT_BUNDLE_IDENTIFIER|CODE_SIGN|DEVELOPMENT_TEAM|PROVISIONING_PROFILE' || true
            exit 1
          fi
          echo "✅ Archive created at: $ARCHIVE_PATH"

      - name: Export IPA
        script: |
          set -e
          mkdir -p "$EXPORT_DIR"
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist "$EXPORT_PLIST" \
            -exportPath "$EXPORT_DIR"
          echo "Artifacts in $EXPORT_DIR:"
          ls -la "$EXPORT_DIR"

    artifacts:
      - Export/*.ipa
      - Export/*.dSYM.zip
      - ExportOptions.plist

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
