workflows:
  ios_release:
    name: FireOpsCalc iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      groups:
        - appstore_connect
      xcode: 16.4
      cocoapods: default
      node: 20.11.1
      vars:
        PRODUCT_BUNDLE_IDENTIFIER: "com.fireopscalc.app"
        DEVELOPMENT_TEAM: "QZ55W58398"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        ARCHIVE_PATH: "$CM_BUILD_DIR/build/App.xcarchive"
        IPA_EXPORT_DIR: "$CM_BUILD_DIR/Export"
        IPA_NAME: "FireOpsCalc.ipa"

    triggering:
      events: [push, tag]
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      - name: Install JS dependencies & sync Capacitor
        script: |
          npm ci || npm install
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install --repo-update
          cd -

      - name: Fetch signing files from Developer Portal
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$PRODUCT_BUNDLE_IDENTIFIER" --type IOS_APP_STORE --create
          keychain add-certificates

      - name: Build Xcode archive (automatic signing)
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            -destination 'generic/platform=iOS' \
            clean archive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$PRODUCT_BUNDLE_IDENTIFIER" \
            CODE_SIGN_STYLE=Automatic \
            CODE_SIGN_IDENTITY="Apple Distribution"

      - name: Export signed IPA
        script: |
          mkdir -p "$IPA_EXPORT_DIR"
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportPath "$IPA_EXPORT_DIR" \
            -exportOptionsPlist <(cat <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store-connect</string>
            <key>teamID</key><string>${DEVELOPMENT_TEAM}</string>
            <key>signingStyle</key><string>automatic</string>
            <key>uploadSymbols</key><true/>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          EOF
          )

          echo "📦 Export complete — contents:"
          ls -la "$IPA_EXPORT_DIR"
          mv "$IPA_EXPORT_DIR"/*.ipa "$IPA_EXPORT_DIR/$IPA_NAME"

    artifacts:
      - "$IPA_EXPORT_DIR/*.ipa"
      - "$ARCHIVE_PATH"
      - "**/dSYMs/**"

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
