workflows:
  ios_release:
    name: iOS Release (App Store / TestFlight)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      xcode: 16.4
      cocoapods: default
      node: 20.11.1
      vars:
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App
        BUNDLE_ID: com.fireopscalc.app
        DEVELOPMENT_TEAM: QZ55W58398
      groups:
        - ios-signing   # contains your P12 password (if any) and other signing secrets

    # Tie publishing auth to your connected integration
    integrations:
      app_store_connect: FireOpsCalc_iOS-KEY

    scripts:
      - name: Show tool versions
        script: |
          xcodebuild -version
          node -v
          pod --version
          security find-identity -p codesigning -v || true

      # Install certs and provisioning profile from Codemagic Team settings
      - name: Install signing assets from app settings
        script: |
          set -e
          keychain initialize
          keychain add-certificates
          profile install
          echo "Using profile: $CM_PROVISIONING_PROFILE_NAME"

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install --repo-update

      - name: Build iOS archive (Release) with MANUAL signing
        script: |
          set -euo pipefail
          ARCHIVE_PATH="$CM_BUILD_DIR/App.xcarchive"
          mkdir -p "$(dirname "$ARCHIVE_PATH")"

          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath "$ARCHIVE_PATH" \
            CODE_SIGN_STYLE=Manual \
            "CODE_SIGN_IDENTITY=Apple Distribution" \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            PROVISIONING_PROFILE_SPECIFIER="$CM_PROVISIONING_PROFILE_NAME" \
            clean archive | xcpretty

      - name: Export IPA (App Store)
        script: |
          set -euo pipefail
          EXPORT_PLIST="$CM_BUILD_DIR/ExportOptions.plist"
          cat > "$EXPORT_PLIST" <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>method</key><string>app-store</string>
              <key>signingStyle</key><string>manual</string>
              <key>teamID</key><string>$DEVELOPMENT_TEAM</string>
              <key>provisioningProfiles</key>
              <dict>
                <key>$BUNDLE_ID</key><string>$CM_PROVISIONING_PROFILE_NAME</string>
              </dict>
              <key>compileBitcode</key><false/>
            </dict>
          </plist>
          EOF

          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportPath "$CM_EXPORT_DIR" \
            -exportOptionsPlist "$EXPORT_PLIST" | xcpretty

    artifacts:
      - $CM_EXPORT_DIR/*.ipa
      - $CM_BUILD_DIR/App.xcarchive
      - $CM_BUILD_DIR/ExportOptions.plist
      - /tmp/xcodebuild_logs/*.log

    publishing:
      app_store_connect:
        auth: integration         # uses integrations.app_store_connect above
        submit_to_testflight: true
