workflows:
  ios-capacitor:
    name: "iOS Capacitor — FIXED XCODEBUILD TARGET ISOLATION"
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      node: 20
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials
      vars:
        APP_IDENTIFIER: com.fireopscalc.app
        XCODE_SCHEME: App

    scripts:
      - name: Install dependencies
        script: |
          npm ci || npm install --legacy-peer-deps

      - name: Build web assets
        script: |
          npm run build || true
          mkdir -p dist
          cp index.html dist/index.html || true

      - name: Sync Capacitor
        script: |
          [ -d ios ] || npx cap add ios
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod repo update
          pod install
          cd ../../

      - name: Generate certificate private key
        script: |
          echo "🔑 Generating CSR private key..."
          CERT_KEY_PATH="$CM_BUILD_DIR/cert_private.key"
          openssl genrsa -out "$CERT_KEY_PATH" 2048
          echo "CERT_KEY_PATH=$CERT_KEY_PATH" >> $CM_ENV

      - name: Fetch signing files
        script: |
          echo "📥 Fetching signing files..."
          app-store-connect fetch-signing-files "$APP_IDENTIFIER" \
            --type IOS_APP_STORE \
            --platform IOS \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --certificate-key "@file:$CERT_KEY_PATH" \
            --p12-password "" \
            --create --delete-stale-profiles --verbose

      - name: Initialize keychain
        script: |
          keychain initialize
          keychain add-certificates

      - name: Detect TEAM_ID and provisioning profile
        script: |
          PROFILE_PATH="$(find "$HOME/Library/MobileDevice/Provisioning Profiles" -name '*.mobileprovision' | head -n 1)"
          /usr/bin/security cms -D -i "$PROFILE_PATH" > "$CM_BUILD_DIR/profile.plist"
          TEAM_ID="$(/usr/libexec/PlistBuddy -c 'Print TeamIdentifier:0' "$CM_BUILD_DIR/profile.plist")"
          PROFILE_NAME="$(/usr/libexec/PlistBuddy -c 'Print Name' "$CM_BUILD_DIR/profile.plist")"
          echo "TEAM_ID=$TEAM_ID" >> $CM_ENV
          echo "PROFILE_NAME=$PROFILE_NAME" >> $CM_ENV
          echo "PROFILE_PATH=$PROFILE_PATH" >> $CM_ENV

      - name: Create isolated signing config
        script: |
          echo "🧩 Creating temporary xcconfig..."
          SIGNING_CONFIG="$CM_BUILD_DIR/signing.xcconfig"
          cat <<EOF > "$SIGNING_CONFIG"
          DEVELOPMENT_TEAM = $TEAM_ID
          CODE_SIGN_IDENTITY = Apple Distribution
          CODE_SIGN_STYLE = Manual
          PROVISIONING_PROFILE_SPECIFIER = $PROFILE_NAME
          PRODUCT_BUNDLE_IDENTIFIER = $APP_IDENTIFIER

          Pods-App.CODE_SIGNING_ALLOWED = NO
          Pods-App.CODE_SIGN_STYLE = Automatic
          Capacitor.CODE_SIGNING_ALLOWED = NO
          Capacitor.CODE_SIGN_STYLE = Automatic
          CapacitorCordova.CODE_SIGNING_ALLOWED = NO
          CapacitorCordova.CODE_SIGN_STYLE = Automatic
          EOF
          echo "Created $SIGNING_CONFIG"

      - name: Clean
        script: |
          xcodebuild clean \
            -workspace ios/App/App.xcworkspace \
            -scheme "$XCODE_SCHEME" \
            -configuration Release

      - name: Archive
        script: |
          echo "🏗 Archiving App only..."
          ARCHIVE_PATH="$CM_BUILD_DIR/App.xcarchive"

          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath "$ARCHIVE_PATH" \
            -sdk iphoneos \
            -xcconfig "$CM_BUILD_DIR/signing.xcconfig" \
            archive COMPILER_INDEX_STORE_ENABLE=NO

      - name: Export IPA
        script: |
          mkdir -p "$CM_BUILD_DIR/ipa"
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/export_options.plist" \
            -exportPath "$CM_BUILD_DIR/ipa"

      - name: Upload to TestFlight
        script: |
          IPA_PATH="$(find "$CM_BUILD_DIR/ipa" -name '*.ipa' | head -n 1)"
          app-store-connect publish \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --path "$IPA_PATH" \
            --submit-to-testflight

    artifacts:
      - "**/*.ipa"
      - "ios/App/build/**"
