workflows:
  ios_release:
    name: FireOpsCalc iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: 16.4
      cocoapods: default
      node: 20.11.1
      vars:
        PRODUCT_BUNDLE_IDENTIFIER: "com.fireopscalc.app"
        DEVELOPMENT_TEAM: "QZ55W58398"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        ARCHIVE_PATH: "$CM_BUILD_DIR/build/App.xcarchive"
        IPA_EXPORT_DIR: "$CM_BUILD_DIR/Export"
        IPA_NAME: "FireOpsCalc.ipa"
      # NOTE: 'team_id' is NOT allowed here. Keep this block minimal:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.fireopscalc.app"

    triggering:
      events: [push, tag]
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      - name: Install JS deps & sync Capacitor
        script: |
          if [ -f package.json ]; then
            npm ci || npm install
          fi
          npx cap sync ios || true

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install --repo-update
          cd -

      - name: Fetch signing files (uses Integration)
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$PRODUCT_BUNDLE_IDENTIFIER" --type IOS_APP_STORE --create
          keychain add-certificates

      - name: Build archive
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            clean archive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$PRODUCT_BUNDLE_IDENTIFIER"

      - name: Create exportOptions.plist (automatic signing)
        script: |
          cat > exportOptions.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>automatic</string>
            <key>destination</key><string>export</string>
            <key>uploadSymbols</key><true/>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          EOF

      - name: Export IPA
        script: |
          mkdir -p "$IPA_EXPORT_DIR"
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportPath "$IPA_EXPORT_DIR" \
            -exportOptionsPlist exportOptions.plist
          if [ -f "$IPA_EXPORT_DIR/$XCODE_SCHEME.ipa" ]; then
            mv "$IPA_EXPORT_DIR/$XCODE_SCHEME.ipa" "$IPA_EXPORT_DIR/$IPA_NAME"
          fi
          ls -la "$IPA_EXPORT_DIR"

    artifacts:
      - "$IPA_EXPORT_DIR/*.ipa"
      - "$ARCHIVE_PATH"
      - "exportOptions.plist"
      - "**/dSYMs/**"

    publishing:
      app_store_connect:
        # <<< IMPORTANT: set this to your real integration name or ID >>>
        integration: "YOUR_INTEGRATION_NAME_OR_ID"
        submit_to_testflight: true
