workflows:
  android-release:
    name: FireOps Calc – Android Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        ANDROID_APP_ID: "com.fireopscalc.app"
        ANDROID_APP_NAME: "FireOps Calc"

    scripts:
      - name: Install Node dependencies
        script: |
          npm install

      # If you have a web build step (like Vite/webpack), it will run.
      # If not, this just prints a message and continues.
      - name: Build web assets
        script: |
          if npm run | grep -q "build"; then
            npm run build
          else
            echo "No npm build script, using existing dist/ folder"
          fi

      - name: Sync Capacitor to Android
        script: |
          npx cap sync android

      - name: Build Android app (AAB + APK)
        working_directory: android
        script: |
          ./gradlew clean bundleRelease assembleRelease

    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - "you@example.com"   # <-- change this to your email
        notify:
          success: true
          failure: true
