workflows:
  ios_release:
    name: FireOpsCalc iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60

    # 👇 This satisfies: publishing.auth: integration
    integrations:
      app_store_connect: FireCalc   # exact name from Teams → Integrations

    environment:
      xcode: 16.4
      cocoapods: default
      node: 20.11.1
      vars:
        PRODUCT_BUNDLE_IDENTIFIER: "com.fireopscalc.app"
        DEVELOPMENT_TEAM: "QZ55W58398"
        WORKSPACE: "ios/App/App.xcworkspace"
        SCHEME: "App"
        ARCHIVE_PATH: "/Users/builder/clone/build/App.xcarchive"
        EXPORT_DIR: "/Users/builder/clone/Export"
        EXPORT_OPTS_PLIST: "/Users/builder/clone/ExportOptions.plist"
        PROVISIONING_PROFILE_SPECIFIER: "FireOpsCalc_AppStore_Profile"
      groups:
        - appstore_connect   # optional; harmless to keep

    cache:
      cache_paths:
        - ~/.npm
        - ~/.cache/CocoaPods
        - ~/Library/Caches/CocoaPods
        - ios/Pods

    scripts:
      - name: Install deps & sync iOS
        script: |
          npm ci || npm install
          npx cap sync ios

      - name: Import code-signing from Codemagic storage
        script: |
          # Uses the p12 and the .mobileprovision you added in Team → Code signing identities
          keychain initialize
          keychain add-certificates
          security find-identity -v

      - name: Create ExportOptions.plist
        script: |
          cat > "$EXPORT_OPTS_PLIST" <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.fireopscalc.app</key>
              <string>FireOpsCalc_AppStore_Profile</string>
            </dict>
            <key>manageAppVersionAndBuildNumber</key><false/>
            <key>stripSwiftSymbols</key><true/>
            <key>uploadSymbols</key><true/>
          </dict>
          </plist>
          PLIST
          cat "$EXPORT_OPTS_PLIST"

      - name: Build Xcode archive (manual signing for App target)
        script: |
          xcodebuild -workspace "$WORKSPACE" \
                     -scheme "$SCHEME" \
                     -configuration Release \
                     -archivePath "$ARCHIVE_PATH" \
                     -destination "generic/platform=iOS" \
                     CODE_SIGN_STYLE=Manual \
                     DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
                     PRODUCT_BUNDLE_IDENTIFIER="$PRODUCT_BUNDLE_IDENTIFIER" \
                     PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_SPECIFIER" \
                     "CODE_SIGN_IDENTITY=Apple Distribution" \
                     clean archive | xcpretty

      - name: Export IPA
        script: |
          mkdir -p "$EXPORT_DIR"
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist "$EXPORT_OPTS_PLIST" \
            -exportPath "$EXPORT_DIR" | xcpretty
          echo "Artifacts in $EXPORT_DIR:"
          ls -la "$EXPORT_DIR"

    artifacts:
      - Export/*.ipa
      - Export/*.dSYM.zip
      - ExportOptions.plist

    publishing:
      app_store_connect:
        auth: integration        # ✅ now valid because integrations.app_store_connect is set
        # set to true to auto-upload; leave false to just produce the IPA
        submit_to_testflight: true
