workflows:
  ios_release:
    name: iOS App Store Release
    instance_type: mac_mini_m2
    max_build_duration: 60

    integrations:
      app_store_connect: FireCalc   # must match the name in Codemagic Team settings

    environment:
      xcode: 16.4
      cocoapods: default
      node: 20.11.1
      vars:
        PRODUCT_BUNDLE_IDENTIFIER: "com.fireopscalc.app"
        DEVELOPMENT_TEAM: "QZ55W58398"
        WORKSPACE: "ios/App/App.xcworkspace"
        SCHEME: "App"
        ARCHIVE_PATH: "/Users/builder/clone/build/App.xcarchive"
        IPA_EXPORT_DIR: "/Users/builder/clone/Export"
        IPA_NAME: "FireOpsCalc.ipa"
      groups:
        - appstore_connect   # ok even if not used directly with integration-auth

    scripts:
      - name: Verify workspace & list schemes
        script: |
          set -euo pipefail
          ls -lah "$WORKSPACE" || (echo "Workspace not found at $WORKSPACE" && exit 1)
          xcodebuild -list -workspace "$WORKSPACE"

      - name: Install dependencies & sync iOS
        script: |
          set -euo pipefail
          npm ci || npm install
          # Skip if no build script
          npm run build || echo "No npm build script; continuing"
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          set -euo pipefail
          cd ios/App
          pod repo update
          pod install
          cd -

      - name: Build Xcode archive (Release)
        script: |
          set -euo pipefail
          xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            -destination "generic/platform=iOS" \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$PRODUCT_BUNDLE_IDENTIFIER" \
            CODE_SIGN_STYLE=Automatic \
            clean archive | xcpretty
          test -d "$ARCHIVE_PATH" || (echo "Archive not created at $ARCHIVE_PATH" && exit 1)

      - name: Create exportOptions.plist
        script: |
          set -euo pipefail
          cat > exportOptions.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>destination</key><string>export</string>
            <key>signingStyle</key><string>automatic</string>
            <key>stripSwiftSymbols</key><true/>
            <key>uploadSymbols</key><true/>
          </dict>
          </plist>
          EOF

      - name: Export signed IPA
        script: |
          set -euo pipefail
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$IPA_EXPORT_DIR" | xcpretty
          ls -lah "$IPA_EXPORT_DIR"
          test -f "$IPA_EXPORT_DIR/$IPA_NAME" || echo "Note: Xcode may name the .ipa after the scheme; any .ipa present will be published."

    artifacts:
      - $IPA_EXPORT_DIR/*.ipa
      - $ARCHIVE_PATH
      - exportOptions.plist

    publishing:
      app_store_connect:
        auth: integration    # uses integrations.app_store_connect: FireCalc
        submit_to_testflight: true
        submit_to_app_store: false
