workflows:
  ios_release:
    name: iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60

    integrations:
      app_store_connect: FireCalc

    environment:
      xcode: 16.4
      ios_signing:
        # Use the exact Codemagic reference name you saved (lowercase in your screenshot)
        provisioning_profiles:
          - FireOpsCalcprofile
      vars:
        DEVELOPMENT_TEAM: QZ55W58398
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App
        ARCHIVE_PATH: $CM_BUILD_DIR/build/App.xcarchive
        EXPORT_DIR: $CM_BUILD_DIR/Export

    cache:
      cache_paths:
        - ~/.npm
        - ~/Library/Caches/CocoaPods
        - ios/Pods -> ios/Podfile.lock
        - ios/App/Pods -> ios/App/Podfile.lock

    scripts:
      - name: Install Node deps
        script: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Capacitor iOS sync (creates Podfile if needed)
        script: |
          npx cap sync ios

      - name: Install CocoaPods (auto-detect Podfile location)
        script: |
          set -e
          if [ -f "ios/App/Podfile" ]; then
            echo "Found Podfile in ios/App — running pod install there"
            cd ios/App
            pod install
          elif [ -f "ios/Podfile" ]; then
            echo "Found Podfile in ios — running pod install there"
            cd ios
            pod install
          else
            echo "No Podfile found after cap sync — skipping pods"
          fi

      - name: Apply signing settings (inject profile)
        script: |
          xcode-project use-profiles
          echo "== Current signing settings =="
          xcode-project show-build-settings | grep -E "PROVISIONING_PROFILE_SPECIFIER|DEVELOPMENT_TEAM|CODE_SIGN_STYLE" || true

      - name: Build archive (manual signing)
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$ARCHIVE_PATH" \
            archive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution"

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist "$CM_EXPORT_OPTIONS" \
            -exportPath "$EXPORT_DIR"

    artifacts:
      - Export/*.ipa
      - $CM_BUILD_DIR/build/*.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
