workflows:
  android-release:
    name: FireOps Calc – Android Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      java: 21
      node: 20
      vars:
        ANDROID_APP_ID: "com.fireopscalc.app"
        ANDROID_APP_NAME: "FireOps Calc"
      android_signing:
        - FireOpsCalcReleaseKey

    scripts:
      - name: Show versions
        script: |
          node -v
          npm -v
          java -version

      - name: Install Node dependencies
        script: |
          npm install

      - name: Build web assets
        script: |
          npm run build

      - name: Sync Capacitor Android
        script: |
          npx cap sync android

      - name: Build signed Android app
        script: |
          cd android
          ./gradlew bundleRelease
