workflows:
  ios_release:
    name: iOS Release (App Store)
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      xcode: 16.4
      cocoapods: default
      node: 18.18.0
      vars:
        # 👇 set these for your project
        BUNDLE_ID: "com.fireopscalc.app"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"

      # ✅ AUTOMATIC SIGNING — pick ONE method only (this one)
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "$BUNDLE_ID"

      # (You already created these secure env vars in Codemagic)
      # APP_STORE_CONNECT_KEY_IDENTIFIER
      # APP_STORE_CONNECT_ISSUER_ID
      # APP_STORE_CONNECT_PRIVATE_KEY
      # APP_STORE_CONNECT_TEAM_ID  (optional but recommended)

    cache:
      cache_paths:
        - ~/.npm
        - ~/.cache/CocoaPods
        - ios/App/Pods

    scripts:
      - name: Clean caches (optional)
        script: |
          rm -rf ~/Library/Caches/CocoaPods Pods ~/Library/Developer/Xcode/DerivedData || true

      - name: Install dependencies
        script: npm ci

      - name: Build web assets
        script: npm run build

      - name: Sync Capacitor iOS
        script: npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install --repo-update

      - name: Build archive (Release)
        script: |
          set -e
          ARCHIVE_PATH="$CM_BUILD_DIR/build/App.xcarchive"
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath "$ARCHIVE_PATH" \
            clean archive | xcpretty

      - name: Export IPA (App Store)
        script: |
          set -e
          EXPORT_PLIST="$CM_BUILD_DIR/exportOptions.plist"
          cat > "$EXPORT_PLIST" <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>automatic</string>
            <key>stripSwiftSymbols</key><true/>
            <key>uploadSymbols</key><true/>
            <key>compileBitcode</key><false/>
            <key>teamID</key><string>${APP_STORE_CONNECT_TEAM_ID}</string>
            <key>destination</key><string>export</string>
            <key>manageAppVersionAndBuildNumber</key><true/>
          </dict>
          </plist>
          EOF

          EXPORT_DIR="$CM_BUILD_DIR/build/ipa"
          mkdir -p "$EXPORT_DIR"
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/App.xcarchive" \
            -exportOptionsPlist "$EXPORT_PLIST" \
            -exportPath "$EXPORT_DIR" | xcpretty

    artifacts:
      - build/ipa/*.ipa
      - build/App.xcarchive

    publishing:
      app_store_connect:
        # ✅ Uses your API key env vars already in Codemagic
        api_key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        private_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
        # team_id is optional but helps if you belong to multiple teams
        team_id: $APP_STORE_CONNECT_TEAM_ID
