workflows:
  ios_release:
    name: FireOpsCalc iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60

    # ✅ this is required because you’re using
    # publishing: app_store_connect: auth: integration
    integrations:
      app_store_connect: FireCalc

    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true

    environment:
      xcode: 16.4
      cocoapods: default
      node: 20.11.1
      vars:
        WORKSPACE: "ios/App/App.xcworkspace"
        SCHEME: "App"
        BUNDLE_ID: "com.fireopscalc.app"
        EXPORT_DIR: "/Users/builder/clone/Export"
        ARCHIVE_PATH: "/Users/builder/clone/build/App.xcarchive"
        IPA_NAME: "FireOpsCalc.ipa"

    scripts:
      - name: 1) Install Node deps & build web
        script: |
          if [ -f package.json ]; then
            if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
              npm ci || npm install
            else
              npm install
            fi
            npm run build --if-present
          else
            echo "No package.json, skipping web build."
          fi

      - name: 2) Capacitor sync iOS
        script: |
          if [ -f capacitor.config.ts ] || [ -f capacitor.config.json ] || [ -f capacitor.config.js ]; then
            npx cap sync ios
          else
            echo "No capacitor config, skipping npx cap sync ios"
          fi
          echo "Contents of ios/App/App:"
          ls -la ios/App/App || true

      - name: 3) Install CocoaPods
        script: |
          cd ios/App
          pod install --repo-update || pod install
          cd ../..

      - name: 4) Fetch signing files from App Store Connect (this fixes CM_PROVISIONING_PROFILES_DIR=empty)
        script: |
          # pulls BOTH the certificate and the provisioning profile from ASC
          app-store-connect fetch-signing-files \
            --type IOS_APP_STORE \
            --bundle-id "$BUNDLE_ID" \
            --certificate-key "FireCalcCertiicate"

          # import the downloaded certificate(s) to keychain
          keychain add-certificates

          # tell Xcode project to actually USE the downloaded profiles
          xcode-project use-profiles

          echo "Provisioning dir content:"
          ls -R "$CM_PROVISIONING_PROFILES_DIR" || true

      - name: 5) Create ExportOptions.plist
        script: |
          EXPORT_PLIST="/Users/builder/export_options.plist"
          rm -f "$EXPORT_PLIST"
          /usr/bin/plutil -create xml1 "$EXPORT_PLIST"
          /usr/libexec/PlistBuddy -c "Add :method string app-store-connect" "$EXPORT_PLIST"
          /usr/libexec/PlistBuddy -c "Add :teamID string QZ55W58398" "$EXPORT_PLIST"
          /usr/libexec/PlistBuddy -c "Add :uploadBitcode bool false" "$EXPORT_PLIST"
          /usr/libexec/PlistBuddy -c "Add :compileBitcode bool false" "$EXPORT_PLIST"
          echo "==== ExportOptions.plist ===="
          /usr/libexec/PlistBuddy -c "Print" "$EXPORT_PLIST"

      - name: 6) Archive (let applied profiles handle signing)
        script: |
          xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath "$ARCHIVE_PATH" \
            archive \
            | xcpretty

      - name: 7) Export IPA
        script: |
          mkdir -p "$EXPORT_DIR"
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist /Users/builder/export_options.plist \
            -exportPath "$EXPORT_DIR" \
            | xcpretty

          IPA_PATH="$(ls -1t "$EXPORT_DIR"/*.ipa 2>/dev/null | head -n 1)"
          if [ -z "$IPA_PATH" ]; then
            echo "❌ No IPA created"
            ls -la "$EXPORT_DIR" || true
            exit 1
          fi

          mv -f "$IPA_PATH" "$EXPORT_DIR/$IPA_NAME"
          echo "✅ IPA at $EXPORT_DIR/$IPA_NAME"

    artifacts:
      - "$EXPORT_DIR/$IPA_NAME"

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
