workflows:
  ios_release:
    name: FireOpsCalc iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: 16.4
      cocoapods: default
      node: 20.11.1

      vars:
        # --- App identity ---
        PRODUCT_BUNDLE_IDENTIFIER: "com.fireopscalc.app"
        DEVELOPMENT_TEAM: "QZ55W58398"

        # --- Xcode project paths ---
        WORKSPACE: "ios/App/App.xcworkspace"
        # If your scheme isn't literally "App", we auto-detect below.
        FALLBACK_SCHEME: "App"

        # --- Archive/Export output paths ---
        ARCHIVE_PATH: "/Users/builder/clone/Export/App.xcarchive"
        EXPORT_DIR: "/Users/builder/clone/Export"
        IPA_NAME: "FireOpsCalc.ipa"

        # --- Signing asset names (MUST match the reference names in Codemagic Team → Code signing) ---
        CM_DISTRIBUTION_CERT_REF: "FireOpsCalc_Distribution_2025"
        CM_APPSTORE_PROFILE_REF: "FireOpsCalc_AppStore_Profile"

    # Pull the certificate & the provisioning profile from Codemagic secure storage
    ios_signing:
      certificates:
        - $CM_DISTRIBUTION_CERT_REF
      provisioning_profiles:
        - $CM_APPSTORE_PROFILE_REF

    scripts:
      - name: Show Xcode version
        script: xcodebuild -version

      - name: Detect available schemes & select one
        script: |
          set -e
          echo "Listing schemes in $WORKSPACE"
          xcodebuild -list -workspace "$WORKSPACE" || true

          SCHEMES_JSON="$(mktemp)"
          xcodebuild -list -json -workspace "$WORKSPACE" > "$SCHEMES_JSON" || true

          # Parse the JSON (python is available on Codemagic images)
          python3 - <<'PY'
import json, os, sys
p = os.environ.get("SCHEMES_JSON")
data = {}
try:
  with open(p) as f: data = json.load(f)
except Exception as e:
  pass
schemes = []
for proj in (data.get("project") or {}).get("schemes", []):
  schemes.append(proj)
# Fallback selection
pick = os.environ.get("FALLBACK_SCHEME","App")
if schemes:
  # Prefer exact 'App' if present, else first scheme
  if "App" in schemes: pick = "App"
  else: pick = schemes[0]
print(f"::set-env name=SCHEME_DETECTED::{pick}")
PY
          # Export for the rest of the steps
          SCHEME_DETECTED="$(grep -o '::set-env name=SCHEME_DETECTED::.*' <(python3 - <<'PY'
import os,sys
print(os.environ.get("SCHEME_DETECTED",""))
PY
) || true)"
          # The above trick won't actually set; so read from the python stdout file:
          SCHEME_DETECTED="$(python3 - <<'PY'
import json, os
print(os.environ.get("FALLBACK_SCHEME","App"))
PY
)"
          # Re-evaluate from the JSON file directly (robust)
          SCHEME_DETECTED=$(python3 - "$SCHEMES_JSON" "$FALLBACK_SCHEME" <<'PY'
import json, sys
j = {}
try:
  with open(sys.argv[1]) as f: j = json.load(f)
except: pass
fallback = sys.argv[2]
schemes = (j.get("project") or {}).get("schemes", [])
pick = fallback
if schemes:
  pick = "App" if "App" in schemes else schemes[0]
print(pick)
PY
)
          echo "Using scheme: $SCHEME_DETECTED"
          echo "SCHEME_DETECTED=$SCHEME_DETECTED" >> $CM_ENV

      - name: Install CocoaPods (if Podfile exists)
        script: |
          set -e
          if [ -f "ios/App/Podfile" ]; then
            cd ios/App
            pod repo update
            pod install
            cd ../../
          else
            echo "No Podfile found — skipping pod install (Capacitor may have vendored pods)."
          fi

      - name: Verify signing files present
        script: |
          set -e
          echo "Listing installed provisioning profiles:"
          ls -lah "$HOME/Library/MobileDevice/Provisioning Profiles" || true
          echo "Search for com.fireopscalc.app in profiles:"
          grep -R "com.fireopscalc.app" "$HOME/Library/MobileDevice/Provisioning Profiles" -n || true

      - name: Build Xcode archive (scoped signing)
        script: |
          set -e
          mkdir -p "$EXPORT_DIR"

          # IMPORTANT: Do NOT set global signing values that bleed into Pods.
          xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME_DETECTED" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            -destination 'generic/platform=iOS' \
            clean archive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$PRODUCT_BUNDLE_IDENTIFIER" \
            CODE_SIGN_IDENTITY= \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER= \
            \
            "CODE_SIGN_IDENTITY[project=App][target=App]=Apple Distribution" \
            "PROVISIONING_PROFILE_SPECIFIER[project=App][target=App]=$CM_APPSTORE_PROFILE_REF" \
            \
            "CODE_SIGNING_ALLOWED[project=Pods]=NO" \
            "CODE_SIGNING_ALLOWED[project=Pods][target=Pods-App]=NO" \
            "CODE_SIGNING_ALLOWED[project=Pods][target=Capacitor]=NO" \
            "CODE_SIGNING_ALLOWED[project=Pods][target=CapacitorCordova]=NO"

      - name: Export IPA (app-store)
        script: |
          set -e
          cat > "$EXPORT_DIR/ExportOptions.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>method</key><string>app-store</string>
  <key>compileBitcode</key><false/>
  <key>signingStyle</key><string>manual</string>
  <key>teamID</key><string>${DEVELOPMENT_TEAM}</string>
  <key>provisioningProfiles</key>
  <dict>
    <key>${PRODUCT_BUNDLE_IDENTIFIER}</key><string>${CM_APPSTORE_PROFILE_REF}</string>
  </dict>
  <key>destination</key><string>export</string>
</dict>
</plist>
EOF

          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportPath "$EXPORT_DIR" \
            -exportOptionsPlist "$EXPORT_DIR/ExportOptions.plist"

          # Rename/copy IPA for artifacts
          if [ -f "$EXPORT_DIR/$SCHEME_DETECTED.ipa" ]; then
            mv "$EXPORT_DIR/$SCHEME_DETECTED.ipa" "$EXPORT_DIR/$IPA_NAME"
          elif [ -f "$EXPORT_DIR/App.ipa" ]; then
            mv "$EXPORT_DIR/App.ipa" "$EXPORT_DIR/$IPA_NAME"
          fi

          if [ ! -f "$EXPORT_DIR/$IPA_NAME" ]; then
            echo "ERROR: IPA not found after export."
            ls -lah "$EXPORT_DIR"
            exit 1
          fi

          echo "IPA at: $EXPORT_DIR/$IPA_NAME"
          echo "APP_IPA_PATH=$EXPORT_DIR/$IPA_NAME" >> $CM_ENV

      # OPTIONAL: Publish with App Store Connect if you later enable an integration key.
      # Keep disabled by default to avoid failures.
      - name: (Optional) Publish to App Store Connect
        script: |
          set -e
          if [ -f "$APP_IPA_PATH" ] && [ -n "$APP_IPA_PATH" ]; then
            echo "IPA ready at $APP_IPA_PATH"
            echo "Skip automatic upload here to keep things explicit. You can enable Publishing in Codemagic UI or add an altool/ASC upload step."
          else
            echo "No IPA found to publish."
          fi

    artifacts:
      - Export/*.ipa
      - Export/*.xcarchive

    publishing:
      # Keep empty so the build won’t fail on publishing.
      scripts:
        - name: Zip artifacts
          script: |
            set -e
            cd "$EXPORT_DIR"
            zip -r "pump_$(printf %03d $CM_BUILD_ID)_artifacts.zip" . || true
