workflows:
  ios-capacitor:
    name: iOS Capacitor → TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      node: 20
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials   # contains: APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_PRIVATE_KEY
      vars:
        APP_IDENTIFIER: com.fireopscalc.app   # <-- your bundle id
        XCODE_SCHEME: App                     # <-- change if your scheme differs
        TEAM_ID: ""                           # <-- optionally set your Apple Team ID (e.g., 1A2BC3D4E5), or leave empty

    scripts:
      - name: Install deps
        script: |
          echo "Node:" && node -v
          npm ci || npm install --legacy-peer-deps

      - name: Build web to dist/
        script: |
          npm run build || true
          if [ ! -f "dist/index.html" ]; then
            mkdir -p dist
            if [ -f "index.html" ]; then
              cp index.html dist/index.html
            else
              echo "dist/index.html missing and no root index.html to copy."
              exit 1
            fi
          fi

      - name: Ensure iOS platform exists & sync
        script: |
          [ -d ios ] || npx cap add ios
          npx cap sync ios

      - name: Debug ASC vars (lengths only)
        script: |
          echo "Key ID len: ${#APP_STORE_CONNECT_KEY_IDENTIFIER} (expect ~10)"
          echo "Issuer ID len: ${#APP_STORE_CONNECT_ISSUER_ID} (expect 36)"
          echo "Private key starts with: ${APP_STORE_CONNECT_PRIVATE_KEY:0:27}"

      - name: Generate certificate private key (for creating new Distribution cert)
        script: |
          CERT_KEY_PATH="$CM_BUILD_DIR/cert_private.key"
          openssl genrsa -out "$CERT_KEY_PATH" 2048
          echo "CERT_KEY_PATH=$CERT_KEY_PATH" >> $CM_ENV

      - name: Fetch signing files from App Store Connect (auto-create using our key)
        script: |
          app-store-connect fetch-signing-files "$APP_IDENTIFIER" \
            --type IOS_APP_STORE \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --certificate-key "@file:$CERT_KEY_PATH" \
            --p12-password "" \
            --create --verbose

      - name: List fetched certs & profiles (debug)
        script: |
          echo "Provisioning Profiles:"
          ls -la "/Users/builder/Library/MobileDevice/Provisioning Profiles" || true
          echo "Certificates:"
          ls -la "/Users/builder/Library/MobileDevice/Certificates" || true

      - name: Initialize keychain & install certs/profiles
        script: |
          keychain initialize
          keychain add-certificates

      - name: Create ExportOptions.plist (automatic signing, app-store)
        script: |
          PLIST_PATH="$CM_BUILD_DIR/export_options.plist"
          {
            echo '<?xml version="1.0" encoding="UTF-8"?>'
            echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">'
            echo '<plist version="1.0"><dict>'
            echo '  <key>method</key><string>app-store</string>'
            echo '  <key>signingStyle</key><string>automatic</string>'
            if [ -n "$TEAM_ID" ]; then
              echo '  <key>teamID</key><string>'"$TEAM_ID"'</string>'
            fi
            echo '  <key>stripSwiftSymbols</key><true/>'
            echo '  <key>uploadSymbols</key><true/>'
            echo '  <key>manageAppVersionAndBuildNumber</key><false/>'
            echo '</dict></plist>'
          } > "$PLIST_PATH"
          echo "ExportOptions at: $PLIST_PATH"

      - name: Build .ipa
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "$XCODE_SCHEME" \
            --export-options-plist "$CM_BUILD_DIR/export_options.plist"

      - name: Publish to TestFlight
        script: |
          IPA_PATH="$(find . -name '*.ipa' | head -n 1)"
          if [ -z "$IPA_PATH" ]; then
            echo "No .ipa found to upload"; exit 1
          fi
          echo "Uploading $IPA_PATH to TestFlight…"
          app-store-connect publish \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --path "$IPA_PATH" \
            --submit-to-testflight

    artifacts:
      - "**/*.ipa"
      - "ios/App/build/**"
