workflows:
  ios_release:
    name: iOS Release (Build & Upload to TestFlight)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: 16.4
      cocoapods: default
      node: 20.11.1

      # --- App identity / paths ---
      vars:
        PRODUCT_BUNDLE_IDENTIFIER: "com.fireopscalc.app"
        DEVELOPMENT_TEAM: "QZ55W58398"
        WORKSPACE: "ios/App/App.xcworkspace"
        SCHEME: "App"
        ARCHIVE_PATH: "/Users/builder/clone/build/App.xcarchive"
        IPA_EXPORT_DIR: "/Users/builder/clone/Export"
        IPA_NAME: "FireOpsCalc.ipa"

      # Let Codemagic fetch and use the proper App Store profile for your bundle id.
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.fireopscalc.app"

    scripts:
      - name: Capacitor sync (ensure bundle id flows into Xcode)
        script: |
          npm ci || npm install
          npx cap sync ios

      - name: Install CocoaPods (if present)
        script: |
          if [ -d "ios/App" ]; then
            cd ios/App
            pod repo update || true
            pod install
            cd ../../
          fi

      - name: Build archive (Automatic signing)
        script: |
          xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            clean archive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$PRODUCT_BUNDLE_IDENTIFIER" \
            CODE_SIGN_STYLE=Automatic \
            | xcpretty

      - name: Export IPA (App Store)
        script: |
          # Create export options on the fly
          cat > /tmp/ExportOptions.plist <<'EOF'
          {
            "method": "app-store",
            "compileBitcode": false,
            "uploadBitcode": false,
            "uploadSymbols": true,
            "destination": "export",
            "stripSwiftSymbols": true
          }
          EOF

          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportPath "$IPA_EXPORT_DIR" \
            -exportOptionsPlist /tmp/ExportOptions.plist \
            | xcpretty

          # Rename the ipa for clarity
          mv "$IPA_EXPORT_DIR"/*.ipa "$IPA_EXPORT_DIR/$IPA_NAME"

    artifacts:
      - Export/*.ipa
      - build/*.xcarchive

    publishing:
      app_store_connect:
        api_key_id: HGYL5BPFZ
        issuer_id: a786600e-e10a-42b2-a2bf-443a1da2554b
        key_name: FireCalc
        submit_to_testflight: true
