workflows:
  ios-capacitor:
    name: iOS Capacitor → TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      node: 20
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials        # your group with the 3 vars
      vars:
        APP_IDENTIFIER: com.fireopscalc.app
        XCODE_SCHEME: App

    scripts:
      - name: Install deps
        script: |
          npm ci || npm install --legacy-peer-deps

      - name: Build web assets
        script: |
          npm run build || true
          [ -f dist/index.html ] || { mkdir -p dist && cp index.html dist/index.html; }

      - name: Ensure iOS platform exists & sync
        script: |
          [ -d ios ] || npx cap add ios
          npx cap sync ios

      - name: Debug ASC vars
        script: |
          echo "Key ID len: ${#APP_STORE_CONNECT_KEY_IDENTIFIER}"
          echo "Issuer ID len: ${#APP_STORE_CONNECT_ISSUER_ID}"
          echo "Private key starts with: ${APP_STORE_CONNECT_PRIVATE_KEY:0:27}"

      # ✅ use built-in signing commands (no flags → version-safe)
      - name: Automatic code signing (App Store Connect API)
        script: |
          keychain initialize
          app-store-connect fetch-profiles
          keychain add-certificates

      - name: Build .ipa
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "$XCODE_SCHEME"

      - name: Publish to TestFlight
        script: |
          IPA_PATH="$(find . -name '*.ipa' | head -n 1)"
          app-store-connect publish \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --path "$IPA_PATH" \
            --submit-to-testflight

    artifacts:
      - "**/*.ipa"
