workflows:
  ios_release:
    name: FireOpsCalc iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      vars:
        WORKSPACE: "ios/App/App.xcworkspace"
        SCHEME: "App"
        ARCHIVE_PATH: "/Users/builder/clone/build/App.xcarchive"
        EXPORT_DIR: "/Users/builder/clone/Export"
        TEAM_ID: "QZ55W58398"
        BUNDLE_ID: "com.fireopscalc.app"

    scripts:
      - name: 1) Sanity check
        script: |
          xcodebuild -list -workspace "$WORKSPACE"

      - name: 2) Archive (let ASC create profiles)
        script: |
          xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath "$ARCHIVE_PATH" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            CODE_SIGN_STYLE=Automatic \
            -allowProvisioningUpdates \
            archive

      - name: 3) Prepare export options
        script: |
          mkdir -p "$EXPORT_DIR"
          /usr/libexec/PlistBuddy -c "Add :method string app-store-connect" exportOptions.plist
          /usr/libexec/PlistBuddy -c "Add :teamID string $TEAM_ID" exportOptions.plist
          /usr/libexec/PlistBuddy -c "Add :signingStyle string automatic" exportOptions.plist
          # If you want to force a specific profile for the app target, uncomment the next 3 lines:
          # /usr/libexec/PlistBuddy -c "Add :provisioningProfiles dict" exportOptions.plist
          # /usr/libexec/PlistBuddy -c "Add :provisioningProfiles:$BUNDLE_ID string FireOpsCalcApp_AppStore" exportOptions.plist
          /usr/libexec/PlistBuddy -c "Print" exportOptions.plist

      - name: 4) Export IPA
        script: |
          if [ ! -d "$(dirname "$ARCHIVE_PATH")" ] || [ ! -e "$ARCHIVE_PATH" ]; then
            echo "❌ Archive not found at $ARCHIVE_PATH"; exit 1
          fi
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$EXPORT_DIR"
          ls -la "$EXPORT_DIR"
