workflows:
  ios_release:
    name: iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60

    integrations:
      app_store_connect: FireCalc

    environment:
      xcode: 16.4
      ios_signing:
        provisioning_profiles:
          - FireOpsCalcprofile
      vars:
        DEVELOPMENT_TEAM: QZ55W58398
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App
        ARCHIVE_PATH: $CM_BUILD_DIR/build/App.xcarchive
        EXPORT_DIR: $CM_BUILD_DIR/Export
        PRODUCT_BUNDLE_IDENTIFIER: com.fireopscalc.app
        PROFILE_SPECIFIER: FireOpsCalcApp_AppStore

    cache:
      cache_paths:
        - ~/.npm
        - ~/Library/Caches/CocoaPods
        - ios/Pods -> ios/Podfile.lock
        - ios/App/Pods -> ios/App/Podfile.lock

    scripts:
      - name: Install Node deps
        script: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Capacitor iOS sync
        script: |
          npx cap sync ios

      - name: Install CocoaPods (auto-detect Podfile)
        script: |
          set -e
          if [ -f "ios/App/Podfile" ]; then
            cd ios/App
            pod install
          elif [ -f "ios/Podfile" ]; then
            cd ios
            pod install
          else
            echo "No Podfile found"
          fi

      - name: Apply stored signing profiles
        script: |
          xcode-project use-profiles

      - name: Build archive (manual signing)
        script: |
          set -e
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$ARCHIVE_PATH" \
            archive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PRODUCT_BUNDLE_IDENTIFIER="$PRODUCT_BUNDLE_IDENTIFIER" \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_SPECIFIER"

      - name: Create export options plist (no provisioningProfiles)
        script: |
          cat <<EOF >ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store-connect</string>
            <key>teamID</key>
            <string>$DEVELOPMENT_TEAM</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>uploadSymbols</key>
            <true/>
            <key>manageAppVersionAndBuildNumber</key>
            <false/>
          </dict>
          </plist>
          EOF

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath "$EXPORT_DIR"

    artifacts:
      - Export/*.ipa
      - $CM_BUILD_DIR/build/*.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
