workflows:
  ios_release:
    name: iOS Release (ASC upload)
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      # Pull the three ASC vars from your variable group that you showed in the screenshot:
      # APP_STORE_CONNECT_PRIVATE_KEY, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_ISSUER_ID
      groups:
        - app_store_credentials     # <-- this must match the Variable Group name in Codemagic UI

      vars:
        # --- App / Xcode ---
        APP_IDENTIFIER: com.fireopscalc.app   # must match the identifier you created in Apple Dev
        TEAM_ID: QZ55W58398                   # your Apple Developer Team ID
        XCODE_SCHEME: App                     # scheme inside ios/App/App.xcworkspace
        XCODE_WORKSPACE: ios/App/App.xcworkspace

        # Optional (kept for clarity)
        CONFIGURATION: Release
        EXPORT_METHOD: app-store

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      # ---------- Preflight: make sure the three ASC vars are present ----------
      - name: Preflight — resolve & verify App Store Connect vars
        script: |
          set -euo pipefail

          require() {
            local key="$1"
            if [ -z "${!key:-}" ]; then
              echo "❌ Missing required env var: $key"; exit 1
            fi
          }

          # These are provided by the variable group "app_store_credentials"
          require APP_STORE_CONNECT_PRIVATE_KEY
          require APP_STORE_CONNECT_KEY_IDENTIFIER
          require APP_STORE_CONNECT_ISSUER_ID

          echo "✅ App Store Connect variables are present."

      # ---------- Install signing from Codemagic Team storage ----------
      # This imports the certificate you generated in Codemagic (“FireOpsCalc Distribution”)
      # and any provisioning profiles you uploaded/fetched (e.g., “FireOpsCalcApp_AppStore”).
      - name: Install code-signing assets from Codemagic
        script: |
          set -euo pipefail
          echo "Creating CI keychain and importing certs/profiles from Codemagic Team…"
          keychain add-certificates
          xcode-project use-profiles

      # ---------- Build IPA (signed) ----------
      - name: Build signed IPA
        script: |
          set -euo pipefail
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --configuration "$CONFIGURATION" \
            --archive \
            --team-id "$TEAM_ID" \
            --export-method "$EXPORT_METHOD"

          echo "Produced IPA(s):"
          ls -lah build/ios/ipa || true

      # ---------- Upload to App Store Connect ----------
      # (No `--submit-to-testflight` flag — your CLI version shows it isn’t supported.)
      - name: Upload to App Store Connect (IPA)
        script: |
          set -euo pipefail

          IPA_PATH="$(ls -1 build/ios/ipa/*.ipa 2>/dev/null | head -n1 || true)"
          if [ -z "$IPA_PATH" ]; then
            echo "❌ No IPA file found to upload!"; exit 1
          fi

          echo "Uploading IPA_PATH = [$IPA_PATH] to App Store Connect…"

          app-store-connect publish \
            --apiKeyId "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --issuerId "$APP_STORE_CONNECT_ISSUER_ID" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --path "$IPA_PATH" \
            --verbose

          echo "✅ Upload finished."

    artifacts:
      - build/ios/ipa/*.ipa
      - build/**/*
      - ~/Library/Logs/scan/*.log

    publishing:
      email:
        recipients:
          - you@example.com
        notify:
          success: true
          failure: true
