# codemagic.yaml
workflows:
  ios_release:
    name: iOS Release (App Store Connect)
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      xcode: 16.4
      cocoapods: default
      node: latest
      ruby: default

      # Codemagic will install these EXACT certificate/profile records
      ios_signing:
        certificates:
          - FireOpsCalc Distribution
        provisioning_profiles:
          - FireOpsCalc App Store Provision

      # App info
      vars:
        APP_IDENTIFIER: com.fireopscalc.app
        TEAM_ID: QZ55W58398
        XCODE_SCHEME: App

        # Fill these in the app's Environment variables page (as Secrets).
        # They should match your ASC key (Key ID 82567339RS, Issuer a786600e-e10a-42b2-a2bf-443a1da2554b).
        APP_STORE_CONNECT_KEY_IDENTIFIER: 82567339RS
        APP_STORE_CONNECT_ISSUER_ID: a786600e-e10a-42b2-a2bf-443a1da2554b
        APP_STORE_CONNECT_PRIVATE_KEY: |
          -----BEGIN PRIVATE KEY-----
          (paste full .p8 key here)
          -----END PRIVATE KEY-----

    scripts:
      - name: Install dependencies (web/app)
        script: |
          set -e
          if [ -f package.json ]; then
            npm ci
            npm run build || true
          fi

      - name: Pod install
        script: |
          set -e
          cd ios/App
          pod repo update
          pod install
          cd ../..

      # Archive WITHOUT overriding signing flags; Codemagic uses the installed
      # "FireOpsCalc Distribution" cert + "FireOpsCalc App Store Provision" profile.
      - name: Archive
        script: |
          set -e
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -destination generic/platform=iOS \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            archive \
            PRODUCT_BUNDLE_IDENTIFIER="$APP_IDENTIFIER" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            | xcpretty

      - name: Prepare export options
        script: |
          cat > "$CM_BUILD_DIR/export_options.plist" <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>method</key><string>app-store</string>
              <key>signingStyle</key><string>manual</string>
              <key>uploadSymbols</key><true/>
              <key>stripSwiftSymbols</key><true/>
            </dict>
          </plist>
          PLIST

      - name: Export IPA
        script: |
          set -e
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/export_options.plist" \
            -exportPath "$CM_BUILD_DIR/ipa" \
            | xcpretty
          ls -lah "$CM_BUILD_DIR/ipa"

      - name: Upload to App Store Connect
        script: |
          set -e
          IPA_PATH="$CM_BUILD_DIR/ipa/App.ipa"
          if [ ! -f "$IPA_PATH" ]; then
            echo "❌ IPA not found at $IPA_PATH"
            exit 1
          fi
          app-store-connect publish \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --path "$IPA_PATH"

    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
      - $CM_BUILD_DIR/App.xcarchive
      - $HOME/Library/Logs/scan/*.log
