workflows:
  ios_release:
    name: iOS Release (App Store)
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      xcode: 16.4
      cocoapods: default
      node: latest
      ruby: default

      # Use signing assets from Codemagic UI (Teams → Code signing identities)
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.fireopscalc.app
        certificates:
          - "FireOpsCalc Distribution"
        provisioning_profiles:
          - "FireOpsCalc App Store Provision"

      # Pull ASC creds from your variable group in the app (Settings → Environment variables)
      groups:
        - app_store_connect   # must contain: APP_STORE_CONNECT_PRIVATE_KEY, APP_STORE_CONNECT_KEY, APP_STORE_CONNECT_ISSU

      # Nice-to-have explicit variables used below
      vars:
        APP_IDENTIFIER: com.fireopscalc.app
        TEAM_ID: QZ55W58398
        XCODE_SCHEME: App
        PROFILE_NAME: FireOpsCalc App Store Provision

    scripts:
      - name: Show Xcode & tool versions
        script: |
          xcodebuild -version
          swift --version
          ruby -v
          node -v
          pod --version

      - name: Install CocoaPods
        script: |
          set -e
          cd ios/App
          pod repo update
          pod install --verbose
          cd ../..

      - name: Clean DerivedData (deflake builds)
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData || true

      - name: Build & Archive (no per-target signing overrides)
        script: |
          set -e
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            clean archive | xcpretty

      - name: Write export options (App Store)
        script: |
          cat > "$CM_BUILD_DIR/export_options.plist" <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>method</key><string>app-store</string>
              <key>signingStyle</key><string>automatic</string>
              <key>uploadSymbols</key><true/>
              <key>stripSwiftSymbols</key><true/>
              <key>compileBitcode</key><false/>
              <key>signingCertificate</key><string>Apple Distribution</string>
              <key>provisioningProfiles</key>
              <dict>
                <key>com.fireopscalc.app</key><string>FireOpsCalc App Store Provision</string>
              </dict>
            </dict>
          </plist>
          PLIST

      - name: Export IPA
        script: |
          set -e
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/export_options.plist" \
            -exportPath "$CM_BUILD_DIR/ipa" | xcpretty
          ls -lah "$CM_BUILD_DIR/ipa"

      - name: Upload to App Store Connect
        script: |
          set -e
          IPA_PATH="$CM_BUILD_DIR/ipa/App.ipa"
          if [ ! -f "$IPA_PATH" ]; then
            echo "❌ IPA not found at $IPA_PATH"; exit 1
          fi
          app-store-connect publish \
            --issuer-id "$APP_STORE_CONNECT_ISSU" \
            --key-id "$APP_STORE_CONNECT_KEY" \
            --private-key "$APP_STORE_CONNECT_PRI" \
            --path "$IPA_PATH"

    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
      - $CM_BUILD_DIR/App.xcarchive

    publishing:
      email:
        recipients:
          - david@yourdomain.example
        notify:
          success: true
          failure: true
