workflows:
  ios_release:
    name: FireOpsCalc iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60

    # ✅ Only this integration is supported/required here
    integrations:
      app_store_connect: FireCalc   # must match the integration name in Codemagic UI

    environment:
      xcode: 16.4
      cocoapods: default
      node: 20.11.1

      vars:
        WORKSPACE: "ios/App/App.xcworkspace"
        SCHEME: "App"
        CONFIGURATION: "Release"
        PRODUCT_BUNDLE_IDENTIFIER: "com.fireopscalc.app"
        DEVELOPMENT_TEAM: "QZ55W58398"
        ARCHIVE_PATH: "/Users/builder/clone/build/App.xcarchive"
        IPA_EXPORT_DIR: "/Users/builder/clone/Export"
        IPA_NAME: "FireOpsCalc.ipa"

      # ✅ Tell Codemagic which signing items to mount
      ios_signing:
        certificates:
          - FireCalcCertiicate
        provisioning_profiles:
          - FireOpsCalcApp_AppStore

    scripts:
      - name: Install pods
        script: |
          set -e
          cd ios/App
          pod install --repo-update || pod install
          cd ../..

      - name: Build & Archive (respect mounted profiles)
        script: |
          set -euo pipefail
          mkdir -p "$(dirname "$ARCHIVE_PATH")"
          /Applications/Xcode-16.4.app/Contents/Developer/usr/bin/xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration "$CONFIGURATION" \
            -destination generic/platform=iOS \
            -archivePath "$ARCHIVE_PATH" \
            archive | xcpretty

      - name: Export IPA (App Store Connect)
        script: |
          set -euo pipefail
          mkdir -p "$IPA_EXPORT_DIR"
          EXPORT_PLIST="/Users/builder/ExportOptions.plist"
          /usr/bin/plutil -create xml1 "$EXPORT_PLIST"
          /usr/libexec/PlistBuddy -c "Add :method string app-store-connect" "$EXPORT_PLIST"
          /usr/libexec/PlistBuddy -c "Add :teamID string $DEVELOPMENT_TEAM" "$EXPORT_PLIST"
          /Applications/Xcode-16.4.app/Contents/Developer/usr/bin/xcodebuild \
            -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist "$EXPORT_PLIST" \
            -exportPath "$IPA_EXPORT_DIR"

    artifacts:
      - "$IPA_EXPORT_DIR/$IPA_NAME"

    publishing:
      app_store_connect:
        auth: integration     # ✅ now valid because of integrations.app_store_connect above
        submit_to_testflight: true
