publishing:
  app_store_connect:
    api_key_id: 4Z6RDP7FH8          # <-- your 10-char Key ID
    issuer_id: 7d852fa2-8afd-47ca-9d37-36d8e66d7b6d  # <-- your Issuer UUID
    private_key: |
      -----BEGIN PRIVATE KEY-----
      ...your full .p8 contents...
      -----END PRIVATE KEY-----
    team_id: AB12C3D4E5            # optional, but good if you’re in multiple teams
    submit_to_testflight: true
