workflows:
  ios-capacitor:
    name: iOS Capacitor → TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      node: 20
      xcode: latest
      cocoapods: default
      # 👇 Load your group so the vars exist in the build environment
      groups:
        - app_store_credentials

    scripts:
      - name: Install deps
        script: |
          echo "Node:" && node -v
          if ! npm ci; then
            echo "npm ci failed, retry with legacy peer deps"
            npm install --legacy-peer-deps
          fi

      - name: Build web to dist/
        script: |
          npm run build || true
          if [ ! -f "dist/index.html" ]; then
            mkdir -p dist
            if [ -f "index.html" ]; then
              cp index.html dist/index.html
            else
              echo "dist/index.html missing and no root index.html to copy."
              exit 1
            fi
          fi

      - name: Ensure iOS platform exists & sync Capacitor
        script: |
          if [ ! -d "ios" ]; then
            echo "iOS platform missing → adding…"
            npx cap add ios
          fi
          npx cap sync ios

      - name: Debug ASC env
        script: |
          echo "ASC Key ID len: ${#APP_STORE_CONNECT_KEY_IDENTIFIER}"
          echo "ASC Issuer ID len: ${#APP_STORE_CONNECT_ISSUER_ID}"
          echo "ASC Private key starts with: ${APP_STORE_CONNECT_PRIVATE_KEY:0:27}"

      - name: Automatic code signing (App Store Connect API)
        script: |
          # Try modern flags first
          if xcode-project use-profiles \
              --api-key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
              --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
              --api-private-key "$APP_STORE_CONNECT_PRIVATE_KEY"; then
            echo "Signing set with modern flags"
          else
            echo "Retrying with legacy flags…"
            xcode-project use-profiles \
              --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
              --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
              --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"
          fi

      - name: Build .ipa
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App" \
            --archive-path "$CM_BUILD_DIR/App.xcarchive"

      - name: Publish to TestFlight
        script: |
          IPA_PATH="$(find . -type f -name '*.ipa' | head -n 1)"
          if [ -z "$IPA_PATH" ]; then
            echo "No .ipa found to upload"; exit 1
          fi
          echo "Uploading $IPA_PATH to TestFlight…"
          app-store-connect publish \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --path "$IPA_PATH" \
            --submit-to-testflight

    artifacts:
      - "**/*.ipa"
      - "ios/App/build/**"
