workflows:
  ios_release:
    name: iOS Release (Automatic signing)
    instance_type: mac_mini_m2
    max_build_duration: 60

    # You already created this in Codemagic → Integrations
    integrations:
      app_store_connect: FireCalc

    environment:
      xcode: 16.4
      cocoapods: default
      vars:
        WORKSPACE: "ios/App/App.xcworkspace"
        SCHEME: "App"
        ARCHIVE_PATH: "/Users/builder/clone/build/App.xcarchive"
        BUNDLE_ID: "com.fireopscalc.app"
        DEV_TEAM: "QZ55W58398"

    scripts:
      - name: Patch Xcode project to **Automatic** signing
        script: |
          set -euo pipefail
          PBX="ios/App/App.xcodeproj/project.pbxproj"

          # Project attributes
          sed -i '' 's/ProvisioningStyle = Manual;/ProvisioningStyle = Automatic;/g' "$PBX"

          # Target (Debug/Release) build settings
          sed -i '' 's/CODE_SIGN_STYLE = Manual;/CODE_SIGN_STYLE = Automatic;/g' "$PBX"

          # Remove any hard-coded profiles so Xcode can manage them
          sed -i '' 's/PROVISIONING_PROFILE_SPECIFIER = [^;]*;/PROVISIONING_PROFILE_SPECIFIER = "";/g' "$PBX"
          sed -i '' 's/PROVISIONING_PROFILE = [^;]*;/PROVISIONING_PROFILE = "";/g' "$PBX"

      - name: Install CocoaPods
        script: |
          set -euo pipefail
          cd ios/App
          pod install --repo-update

      - name: Build Xcode archive (Release)
        script: |
          set -euo pipefail
          xcodebuild -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            -destination generic/platform=iOS \
            -allowProvisioningUpdates \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM="$DEV_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            clean archive

      - name: Export signed IPA (app-store)
        script: |
          set -euo pipefail
          EXPORT_DIR="/Users/builder/clone/Export"
          mkdir -p "$EXPORT_DIR"

          cat > exportOptions.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>method</key><string>app-store</string>
              <key>destination</key><string>export</string>
              <key>compileBitcode</key><false/>
              <key>stripSwiftSymbols</key><true/>
              <key>signingStyle</key><string>automatic</string>
            </dict>
          </plist>
          PLIST

          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportPath "$EXPORT_DIR" \
            -exportOptionsPlist exportOptions.plist

    artifacts:
      - /Users/builder/clone/Export/*.ipa
      - /Users/builder/clone/build/*.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - External Testers

