scripts:
  - name: Show schemes (sanity check)
    script: |
      xcodebuild -list -workspace ios/App/App.xcworkspace

  - name: CocoaPods
    script: |
      set -euo pipefail
      cd ios/App
      pod repo update
      pod install
      cd ../../

  - name: Archive (ASC automatic signing)
    script: |
      set -euo pipefail
      ARCHIVE_PATH="$CM_BUILD_DIR/build/App.xcarchive"
      xcodebuild -workspace "ios/App/App.xcworkspace" \
        -scheme "App" \
        -configuration Release \
        -destination "generic/platform=iOS" \
        -archivePath "$ARCHIVE_PATH" \
        DEVELOPMENT_TEAM="QZ55W58398" \
        PRODUCT_BUNDLE_IDENTIFIER="com.fireopscalc.app" \
        CODE_SIGN_STYLE=Automatic \
        -allowProvisioningUpdates \
        archive | xcpretty
      # Prove the archive exists
      echo "Archive contents:"
      /usr/bin/find "$CM_BUILD_DIR/build" -maxdepth 2 -name "*.xcarchive" -print

  - name: Export IPA (App Store Connect)
    script: |
      set -euo pipefail
      ARCHIVE_PATH="$CM_BUILD_DIR/build/App.xcarchive"
      EXPORT_DIR="$CM_BUILD_DIR/build/Export"
      mkdir -p "$EXPORT_DIR"

      cat > ExportOptions.plist <<'PLIST'
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
        <key>method</key><string>app-store-connect</string>
        <key>signingStyle</key><string>automatic</string>
        <key>uploadSymbols</key><true/>
        <key>uploadBitcode</key><false/>
      </dict>
      </plist>
      PLIST

      # Fail early if the archive isn't there
      test -d "$ARCHIVE_PATH" || { echo "❌ Archive not found at $ARCHIVE_PATH"; exit 1; }

      xcodebuild -exportArchive \
        -archivePath "$ARCHIVE_PATH" \
        -exportPath "$EXPORT_DIR" \
        -exportOptionsPlist ExportOptions.plist \
        -allowProvisioningUpdates | xcpretty

      echo "Exported files:"
      ls -la "$EXPORT_DIR"
