workflows:
  ios_release:
    name: FireOpsCalc iOS Release (App Store)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: 16.4
      cocoapods: default
      node: 20.11.1

      vars:
        PRODUCT_BUNDLE_IDENTIFIER: "com.fireopscalc.app"
        DEVELOPMENT_TEAM: "QZ55W58398"

        # Xcode paths
        WORKSPACE: "ios/App/App.xcworkspace"
        ARCHIVE_PATH: "/Users/builder/clone/build/App.xcarchive"
        IPA_EXPORT_DIR: "/Users/builder/clone/Export"
        IPA_NAME: "FireOpsCalc.ipa"

      ios_signing:
        # These must match exactly what you created in Codemagic Team settings
        certificates:
          - FireOpsCalc_Distribution_2025
        provisioning_profiles:
          - FireOpsCalc_AppStore_Profile

    scripts:
      - name: Install JS deps & sync Capacitor iOS
        script: |
          npm ci
          npx cap sync ios

      - name: Install CocoaPods (in the correct folder)
        script: |
          cd ios/App
          pod repo update
          pod install
          cd ../..

      - name: Detect Xcode scheme
        script: |
          echo "Listing schemes in $WORKSPACE"
          xcodebuild -list -json -workspace "$WORKSPACE" | tee schemes.json
          SCHEME_DETECTED=$(python3 - <<'PY'
import json,sys
d=json.load(open('schemes.json'))
schemes = d.get('workspace',{}).get('schemes',[])
print(schemes[0] if schemes else "")
PY
)
          if [ -z "$SCHEME_DETECTED" ]; then
            echo "No shared scheme found in workspace. Please open ios/App/App.xcworkspace locally and share the App scheme (Product > Scheme > Manage Schemes > check 'Shared')."
            exit 1
          fi
          echo "Using scheme: $SCHEME_DETECTED"
          echo "SCHEME_DETECTED=$SCHEME_DETECTED" >> $CM_ENV

      - name: Build Xcode archive
        script: |
          xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME_DETECTED" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            -destination 'generic/platform=iOS' \
            clean archive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$PRODUCT_BUNDLE_IDENTIFIER" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="FireOpsCalc_AppStore_Profile"

      - name: Create exportOptions.plist
        script: |
          cat > exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>teamID</key><string>${DEVELOPMENT_TEAM}</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>${PRODUCT_BUNDLE_IDENTIFIER}</key><string>FireOpsCalc_AppStore_Profile</string>
            </dict>
            <key>compileBitcode</key><false/>
            <key>manageAppVersionAndBuildNumber</key><true/>
          </dict>
          </plist>
          EOF

      - name: Export IPA (sign & verify)
        script: |
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$IPA_EXPORT_DIR"
          ls -lah "$IPA_EXPORT_DIR"

    artifacts:
      - Export/*.ipa
      - Export/*.pkg
      - build/**/*.dSYM.zip
      - build/**/*.app
      - exportOptions.plist
      - schemes.json
