workflows:
  ios-capacitor:
    name: iOS Capacitor → TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      node: 20
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials       # your group with the three ASC vars
      vars:
        APP_IDENTIFIER: com.fireopscalc.app    # your bundle ID
        XCODE_SCHEME: App                      # change if your scheme differs

    scripts:
      - name: Install deps
        script: |
          npm ci || npm install --legacy-peer-deps

      - name: Build web to dist/
        script: |
          npm run build || true
          [ -f dist/index.html ] || { mkdir -p dist && cp index.html dist/index.html; }

      - name: Ensure iOS platform exists & sync
        script: |
          [ -d ios ] || npx cap add ios
          npx cap sync ios

      - name: Debug ASC vars
        script: |
          echo "Key ID len: ${#APP_STORE_CONNECT_KEY_IDENTIFIER}"
          echo "Issuer ID len: ${#APP_STORE_CONNECT_ISSUER_ID}"
          echo "Private key starts with: ${APP_STORE_CONNECT_PRIVATE_KEY:0:27}"

      - name: Fetch signing files from App Store Connect (try all known flags)
        script: |
          for FLAG in identifier app-id bundle-id app-identifier; do
            echo "Trying flag --$FLAG..."
            if app-store-connect fetch-signing-files \
                --type IOS_APP_STORE \
                --$FLAG "$APP_IDENTIFIER" \
                --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
                --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
                --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
                --create; then
              echo "✅ fetch-signing-files succeeded with --$FLAG"
              break
            fi
          done

      - name: Initialize keychain & install certs/profiles
        script: |
          keychain initialize
          keychain add-certificates

      - name: Build .ipa
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "$XCODE_SCHEME"

      - name: Publish to TestFlight
        script: |
          IPA_PATH="$(find . -name '*.ipa' | head -n 1)"
          app-store-connect publish \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --path "$IPA_PATH" \
            --submit-to-testflight

    artifacts:
      - "**/*.ipa"
      - "ios/App/build/**"
