workflows:
  ios_release:
    name: iOS Release Build & Upload
    instance_type: mac_mini_m2
    max_build_duration: 60

    integrations:
      app_store_connect: FireCalc

    environment:
      xcode: 16.4
      ios_signing:
        provisioning_profiles:
          - FireOpsCalcprofile
      vars:
        DEVELOPMENT_TEAM: QZ55W58398
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App
        ARCHIVE_PATH: $CM_BUILD_DIR/build/App.xcarchive
        EXPORT_PATH: $CM_BUILD_DIR/Export
        PRODUCT_BUNDLE_IDENTIFIER: com.fireopscalc.app
        PROFILE_SPECIFIER: FireOpsCalcApp_AppStore

    cache:
      cache_paths:
        - ~/.npm
        - ~/Library/Caches/CocoaPods
        - ios/Pods -> ios/Podfile.lock
        - ios/App/Pods -> ios/App/Podfile.lock

    scripts:
      - name: Install Node dependencies
        script: |
          npm ci || npm install

      - name: Capacitor sync (push corrected bundle id into Xcode)
        script: |
          # Make sure you changed BOTH:
          # 1) capacitor.config.* -> appId: com.fireopscalc.app
          # 2) ios/App/config.xml  -> <widget id="com.fireopscalc.app" ...>
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          if [ -f "ios/App/Podfile" ]; then
            cd ios/App && pod install
          elif [ -f "ios/Podfile" ]; then
            cd ios && pod install
          else
            echo "No Podfile found (ok if project doesn't use Pods)"
          fi

      - name: Apply stored signing profile(s)
        script: |
          xcode-project use-profiles

      - name: Build archive (manual signing)
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$ARCHIVE_PATH" \
            archive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PRODUCT_BUNDLE_IDENTIFIER="$PRODUCT_BUNDLE_IDENTIFIER" \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_SPECIFIER"

      - name: VERIFY archived bundle id (must equal com.fireopscalc.app)
        script: |
          APP_PLIST="$ARCHIVE_PATH/Products/Applications/App.app/Info.plist"
          if [ ! -f "$APP_PLIST" ]; then
            echo "Could not find Info.plist in archive: $APP_PLIST"
            ls -R "$ARCHIVE_PATH" || true
            exit 1
          fi
          ACTUAL=$(/usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" "$APP_PLIST" 2>/dev/null || true)
          echo "Archived CFBundleIdentifier: '$ACTUAL'"
          if [ "$ACTUAL" != "com.fireopscalc.app" ]; then
            echo "ERROR: Archive bundle id ('$ACTUAL') does not match expected 'com.fireopscalc.app'."
            echo "Fix capacitor.config.* (appId) and ios/App/config.xml (widget id), then re-run."
            exit 1
          fi

      - name: Create ExportOptions.plist (map ONLY app bundle to profile)
        script: |
          cat <<EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store-connect</string>
            <key>teamID</key>
            <string>$DEVELOPMENT_TEAM</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.fireopscalc.app</key>
              <string>FireOpsCalcApp_AppStore</string>
            </dict>
            <key>stripSwiftSymbols</key>
            <true/>
            <key>uploadSymbols</key>
            <true/>
            <key>manageAppVersionAndBuildNumber</key>
            <false/>
            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath "$EXPORT_PATH"

    artifacts:
      - Export/*.ipa
      - $CM_BUILD_DIR/build/*.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
