workflows:
  ios_release:
    name: FireOpsCalc iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60

    # Required because publishing.auth uses "integration"
    integrations:
      app_store_connect: FireCalc   # <— exact name of your ASC integration

    environment:
      xcode: 16.4
      cocoapods: default
      node: 20.11.1
      vars:
        PRODUCT_BUNDLE_IDENTIFIER: "com.fireopscalc.app"
        DEVELOPMENT_TEAM: "QZ55W58398"
        WORKSPACE: "ios/App/App.xcworkspace"
        SCHEME: "App"
        ARCHIVE_PATH: "/Users/builder/clone/build/App.xcarchive"
        EXPORT_DIR: "/Users/builder/clone/Export"
        EXPORT_PLIST: "/Users/builder/clone/ExportOptions.plist"
        # Must match the profile NAME your Xcode project expects (Option A):
        PROVISIONING_PROFILE_SPECIFIER: "FireOpsCalcApp_AppStore"
        # Set app version/build if not set in project:
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
      groups:
        - appstore_connect   # <— all variables live here

    cache:
      cache_paths:
        - ~/.npm
        - ~/.cache/CocoaPods
        - ~/Library/Caches/CocoaPods
        - ios/Pods

    scripts:
      # Resilient: works even if no "build" script is defined in package.json
      - name: Install deps, stage web assets, sync iOS
        script: |
          set -e
          npm ci || npm install

          # Try to build if a "build" script exists
          if npm run 2>/dev/null | grep -qE '^\s*build\s'; then
            echo "Found build script → running npm run build"
            npm run build
            WEB_OUT="dist"
          else
            echo "No build script -> looking for existing assets"
            if [ -d "dist" ]; then WEB_OUT="dist";
            elif [ -d "www" ]; then WEB_OUT="www";
            elif [ -d "public" ]; then
              echo "Using public/ as web root → copying to dist/"
              rsync -a --delete public/ dist/
              WEB_OUT="dist"
            else
              echo "No dist/www/public found → creating a minimal placeholder site"
              mkdir -p dist
              cat > dist/index.html <<'HTML'
              <!doctype html>
              <html>
                <head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/>
                  <title>FireOpsCalc</title>
                  <style>body{font-family:system-ui,Arial,sans-serif;padding:24px}code{background:#f4f4f4;padding:2px 6px;border-radius:4px}</style>
                </head>
                <body>
                  <h1>FireOpsCalc</h1>
                  <p>Placeholder web assets for Capacitor build. Replace with your real bundle.</p>
                </body>
              </html>
              HTML
              WEB_OUT="dist"
            fi
          fi

          echo "Web output at: $WEB_OUT"
          # Copy/sync assets into iOS project
          npx cap copy ios
          cd ios/App
          pod install --repo-update
          cd -

      - name: Stage signing files & import p12 (with private key)
        script: |
          set -e
          : "${IOS_CERTIFICATE_P12_BASE64:?Missing IOS_CERTIFICATE_P12_BASE64}"
          : "${IOS_CERTIFICATE_PASSWORD:?Missing IOS_CERTIFICATE_PASSWORD}"
          : "${IOS_PROVISIONING_PROFILE_BASE64:?Missing IOS_PROVISIONING_PROFILE_BASE64}"

          BUILD_DIR="$PWD"
          CERT_PATH="$BUILD_DIR/fireopscalc_distribution_2025.p12"
          PROV_PATH="$BUILD_DIR/FireOpsCalcApp_AppStore.mobileprovision"

          # Decode Base64 (works on both GNU and macOS)
          echo "$IOS_CERTIFICATE_P12_BASE64"       | base64 --decode > "$CERT_PATH"       || echo "$IOS_CERTIFICATE_P12_BASE64"       | base64 -D > "$CERT_PATH"
          echo "$IOS_PROVISIONING_PROFILE_BASE64"  | base64 --decode > "$PROV_PATH"       || echo "$IOS_PROVISIONING_PROFILE_BASE64"  | base64 -D > "$PROV_PATH"

          # Initialize keychain and import p12 WITH password (handles spaces)
          keychain initialize
          security import "$CERT_PATH" \
            -k "$(security default-keychain | tr -d '"')" \
            -P "$IOS_CERTIFICATE_PASSWORD" -A -T /usr/bin/codesign -T /usr/bin/security

          # Install provisioning profile to the system location
          UUID=$(/usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin <<< "$(security cms -D -i "$PROV_PATH")")
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          cp "$PROV_PATH" "$HOME/Library/MobileDevice/Provisioning Profiles/${UUID}.mobileprovision"

          echo "🔐 Identities in keychain:"
          security find-identity -v "$(security default-keychain | tr -d '"')" || true
          echo "📄 Provisioning profile installed: $UUID.mobileprovision"

      - name: Create ExportOptions.plist (manual signing with fixed profile name)
        script: |
          set -e
          cat > "$EXPORT_PLIST" <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.fireopscalc.app</key>
              <string>FireOpsCalcApp_AppStore</string>
            </dict>
            <key>stripSwiftSymbols</key><true/>
            <key>uploadSymbols</key><true/>
          </dict>
          </plist>
          PLIST
          /usr/libexec/PlistBuddy -c "Print" "$EXPORT_PLIST" || true

      - name: Build archive (manual signing for App target)
        script: |
          set -eo pipefail
          WHAT="-workspace $WORKSPACE"
          echo "Building with: $WHAT, scheme: $SCHEME"

          xcodebuild $WHAT \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            -destination "generic/platform=iOS" \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$PRODUCT_BUNDLE_IDENTIFIER" \
            PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_SPECIFIER" \
            "CODE_SIGN_IDENTITY=Apple Distribution" \
            MARKETING_VERSION="$MARKETING_VERSION" \
            CURRENT_PROJECT_VERSION="$CURRENT_PROJECT_VERSION" \
            clean archive

          if [ ! -d "$ARCHIVE_PATH" ]; then
            echo "❌ Archive not produced at $ARCHIVE_PATH"
            xcodebuild $WHAT -list || true
            xcodebuild $WHAT -scheme "$SCHEME" -showBuildSettings | \
              grep -E 'PRODUCT_NAME|PRODUCT_BUNDLE_IDENTIFIER|CODE_SIGN|DEVELOPMENT_TEAM|PROVISIONING_PROFILE|MARKETING_VERSION|CURRENT_PROJECT_VERSION' || true
            exit 1
          fi
          echo "✅ Archive created: $ARCHIVE_PATH"

      - name: Export IPA
        script: |
          set -e
          mkdir -p "$EXPORT_DIR"
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist "$EXPORT_PLIST" \
            -exportPath "$EXPORT_DIR"
          echo "Artifacts in $EXPORT_DIR:"
          ls -la "$EXPORT_DIR"

    artifacts:
      - Export/*.ipa
      - Export/*.dSYM.zip
      - ExportOptions.plist

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
