- name:  Export IPA (App Store Connect)
  script: |
    set -euo pipefail

    # 1) Locate the archive created by the previous step
    # Prefer the standard path first, then fall back to a search.
    ARCHIVE_PATH="/Users/builder/clone/build/App.xcarchive"
    if [ ! -d "$ARCHIVE_PATH" ]; then
      echo "Archive not at $ARCHIVE_PATH — searching..."
      ARCHIVE_PATH="$(find /Users/builder/clone -maxdepth 3 -type d -name '*.xcarchive' | head -n1 || true)"
    fi

    if [ -z "${ARCHIVE_PATH:-}" ] || [ ! -d "$ARCHIVE_PATH" ]; then
      echo "❌ No .xcarchive found. Check that the ARCHIVE step succeeded."
      exit 1
    fi

    echo "✅ Using archive: $ARCHIVE_PATH"

    # 2) Prepare export destination
    EXPORT_DIR="/Users/builder/clone/Export"
    mkdir -p "$EXPORT_DIR"

    # 3) Create export options (App Store Connect)
    /usr/libexec/PlistBuddy -c "Clear dict" exportOptions.plist >/dev/null 2>&1 || true
    /usr/libexec/PlistBuddy -c "Add :method string app-store-connect" exportOptions.plist
    /usr/libexec/PlistBuddy -c "Add :signingStyle string automatic" exportOptions.plist
    /usr/libexec/PlistBuddy -c "Add :uploadSymbols boolean YES" exportOptions.plist
    /usr/libexec/PlistBuddy -c "Add :destination string export" exportOptions.plist

    echo "Export options:"
    /usr/libexec/PlistBuddy -c "Print" exportOptions.plist

    # 4) Export
    xcodebuild -exportArchive \
      -archivePath "$ARCHIVE_PATH" \
      -exportOptionsPlist exportOptions.plist \
      -exportPath "$EXPORT_DIR"

    echo "Contents of $EXPORT_DIR:"
    ls -la "$EXPORT_DIR"
