workflows:
  ios_release:
    name: "iOS App Store build"
    max_build_duration: 60

    environment:
      groups:
        - appstore_connect        # <- your env group name in Codemagic
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"

    scripts:
      - name: Install signing assets (p12 + provisioning profile)
        script: |
          set -e

          echo "Checking env vars…"
          if [ -z "$IOS_CERTIFICATE_BASE64" ]; then
            echo "❌ IOS_CERTIFICATE_BASE64 is EMPTY"
            exit 1
          fi

          if [ -z "$IOS_PROVISION_PROFILE_BASE64" ]; then
            echo "❌ IOS_PROVISION_PROFILE_BASE64 is EMPTY"
            exit 1
          fi

          if [ -z "$IOS_CERTIFICATE_PASSWORD" ]; then
            echo "❌ IOS_CERTIFICATE_PASSWORD is EMPTY"
            exit 1
          fi

          echo "Decoding certificate and provisioning profile…"
          echo "$IOS_CERTIFICATE_BASE64" | base64 --decode > certificate.p12
          echo "$IOS_PROVISION_PROFILE_BASE64" | base64 --decode > provisioning.mobileprovision

          echo "Importing certificate…"
          security import certificate.p12 \
            -P "$IOS_CERTIFICATE_PASSWORD" \
            -A -t cert -f pkcs12 \
            -k ~/Library/Keychains/login.keychain-db

          echo "Installing provisioning profile…"
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp provisioning.mobileprovision \
            ~/Library/MobileDevice/Provisioning\ Profiles/app.mobileprovision

          echo "✅ Signing assets installed"

      - name: Build Xcode archive
        script: |
          xcode-project build-archive \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --archive-path "$CM_BUILD_DIR/App.xcarchive"

      - name: Export IPA
        script: |
          xcode-project export-archive \
            --archive-path "$CM_BUILD_DIR/App.xcarchive" \
            --export-method app-store

    artifacts:
      - $CM_BUILD_DIR/**

    publishing:
      app_store_connect:
        apple_id: "YOUR_APPLE_ID_EMAIL_HERE"
        submit_to_app_store: false
        submit_to_testflight: true
