workflows:
  android-release:
    name: FireOps Calc – Android Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      java: 21
      node: 20
      vars:
        ANDROID_APP_ID: "com.fireopscalc.app"
        ANDROID_APP_NAME: "FireOps Calc"
      # This must match the name under Code signing → Android keystores in Codemagic
      android_signing:
        - FireOpsCalcReleaseKey

    scripts:
      - name: Show versions
        script: |
          node -v
          npm -v
          java -version

      - name: Install Node dependencies
        script: |
          npm install

      - name: Build web assets (copy FireOps Calc into dist/)
        script: |
          npm run build

      - name: Sync Capacitor Android
        script: |
          npx cap sync android

      - name: Build signed Android App Bundle
        script: |
          cd android
          ./gradlew clean bundleRelease

    artifacts:
      - android/app/build/outputs/bundle/release/*.aab

    publishing:
      email:
        recipients:
          - "you@example.com"   # <-- change to your email if you want notifications
        notify:
          success: true
          failure: true
