workflows:
  ios_release:
    name: FireOpsCalc iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60

    integrations:
      app_store_connect: FireCalc

    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true

    environment:
      xcode: 16.4
      cocoapods: default
      node: 20.11.1
      vars:
        WORKSPACE: "ios/App/App.xcworkspace"
        SCHEME: "App"
        BUNDLE_ID: "com.fireopscalc.app"
        TEAM_ID: "QZ55W58398"
        ARCHIVE_DIR: "/Users/builder/clone/build"
        ARCHIVE_PATH: "/Users/builder/clone/build/App.xcarchive"
        EXPORT_DIR: "/Users/builder/clone/Export"
        IPA_NAME: "FireOpsCalc.ipa"

    scripts:
      - name: 0) Show what Codemagic mounted
        script: |
          echo "=== 0) Mounted signing stuff ==="
          echo "CM_PROVISIONING_PROFILES_DIR=$CM_PROVISIONING_PROFILES_DIR"
          if [ -n "$CM_PROVISIONING_PROFILES_DIR" ] && [ -d "$CM_PROVISIONING_PROFILES_DIR" ]; then
            ls -la "$CM_PROVISIONING_PROFILES_DIR" || true
          else
            echo "⚠️ No profiles visible yet (this is what was causing 'App.app requires a provisioning profile')"
          fi
          echo "=== 0b) Show mobiledevice certs ==="
          ls -la /Users/builder/Library/MobileDevice/Certificates 2>/dev/null || true

      - name: 1) Fetch signing from App Store Connect (best effort)
        script: |
          set +e
          echo "=== 1a) ASC fetch app-store ==="
          app-store-connect fetch-signing-files com.fireopscalc.app \
            --type IOS_APP_STORE \
            --create \
            || echo "⚠️ ASC app-store fetch failed (ok, continue)"

          echo "=== 1b) ASC fetch dev (optional) ==="
          app-store-connect fetch-signing-files com.fireopscalc.app \
            --type IOS_APP_DEVELOPMENT \
            --create \
            || echo "⚠️ ASC dev fetch failed (ok, continue)"

          echo "=== 1c) import certs to keychain ==="
          keychain add-certificates || echo "⚠️ keychain add-certificates failed"

          echo "=== 1d) apply profiles to Xcode project (if present) ==="
          xcode-project use-profiles || echo "⚠️ xcode-project use-profiles failed (usually means no mounted profiles)"

          echo "=== 1e) AFTER FETCH, show again ==="
          echo "CM_PROVISIONING_PROFILES_DIR=$CM_PROVISIONING_PROFILES_DIR"
          if [ -n "$CM_PROVISIONING_PROFILES_DIR" ] && [ -d "$CM_PROVISIONING_PROFILES_DIR" ]; then
            ls -R "$CM_PROVISIONING_PROFILES_DIR" || true
          else
            echo "❌ STILL EMPTY — Codemagic didn’t mount a profile, export will complain later."
          fi
          set -e

      - name: 2) Install Node deps & build web
        script: |
          if [ -f package.json ]; then
            if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
              npm ci || npm install
            else
              npm install
            fi
            npm run build --if-present
          else
            echo "No package.json, skipping web build."
          fi

      - name: 3) Capacitor sync iOS
        script: |
          if [ -f capacitor.config.ts ] || [ -f capacitor.config.json ] || [ -f capacitor.config.js ]; then
            npx cap sync ios
          else
            echo "No capacitor config, skipping npx cap sync ios"
          fi
          echo "=== ios/App/App after sync ==="
          ls -la ios/App/App || true

      - name: 4) Install CocoaPods
        script: |
          set -e
          cd ios/App
          pod install --repo-update || pod install
          cd ../..

      - name: 5) Create ExportOptions.plist
        script: |
          set -e
          EXPORT_PLIST="/Users/builder/export_options.plist"
          rm -f "$EXPORT_PLIST"
          /usr/bin/plutil -create xml1 "$EXPORT_PLIST"
          /usr/libexec/PlistBuddy -c "Add :method string app-store" "$EXPORT_PLIST"
          /usr/libexec/PlistBuddy -c "Add :teamID string $TEAM_ID" "$EXPORT_PLIST"
          /usr/libexec/PlistBuddy -c "Add :uploadBitcode bool false" "$EXPORT_PLIST"
          /usr/libexec/PlistBuddy -c "Add :compileBitcode bool false" "$EXPORT_PLIST"
          echo "=== ExportOptions.plist ==="
          /usr/libexec/PlistBuddy -c "Print" "$EXPORT_PLIST"

      - name: 6) Show build settings (to see signing error in plain text)
        script: |
          echo "=== 6) xcodebuild -showBuildSettings (this will tell us EXACTLY what signing Xcode thinks it has) ==="
          xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -showBuildSettings | grep -E "CODE_SIGN|DEVELOPMENT_TEAM|PRODUCT_BUNDLE_IDENTIFIER|PROVISIONING" || true

      - name: 7) Archive with Xcode (no xcpretty, make dir first)
        script: |
          set -e
          mkdir -p "$ARCHIVE_DIR"
          echo "=== 7) xcodebuild archive (raw output) ==="
          xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath "$ARCHIVE_PATH" \
            archive

          if [ ! -d "$ARCHIVE_PATH" ]; then
            echo "❌ Archive was not created at $ARCHIVE_PATH"
            ls -R "$ARCHIVE_DIR" || true
            exit 1
          fi
          echo "✅ Archive created at $ARCHIVE_PATH"

      - name: 8) Export IPA
        script: |
          set -e
          mkdir -p "$EXPORT_DIR"
          echo "=== 8) xcodebuild exportArchive ==="
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist /Users/builder/export_options.plist \
            -exportPath "$EXPORT_DIR"

          IPA_PATH="$(ls -1t "$EXPORT_DIR"/*.ipa 2>/dev/null | head -n 1)"
          if [ -z "$IPA_PATH" ]; then
            echo "❌ No IPA created"
            ls -la "$EXPORT_DIR" || true
            exit 1
          fi
          mv -f "$IPA_PATH" "$EXPORT_DIR/$IPA_NAME"
          echo "✅ IPA at $EXPORT_DIR/$IPA_NAME"

    artifacts:
      - "$EXPORT_DIR/$IPA_NAME"

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
