workflows:
  ios_release:
    name: iOS Release (EMSCodeSim Team)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: 16.4
      cocoapods: default
      node: 20.11.1
      vars:
        PRODUCT_BUNDLE_IDENTIFIER: "com.fireopscalc.app"
        DEVELOPMENT_TEAM: "QZ55W58398"
        WORKSPACE: "ios/App/App.xcworkspace"
        SCHEME: "App"

        ARCHIVE_PATH: "/Users/builder/clone/build/App.xcarchive"
        DERIVED_DATA: "/Users/builder/clone/DerivedData"
        IPA_EXPORT_DIR: "/Users/builder/clone/Export"
        IPA_NAME: "FireOpsCalc.ipa"

      ios_signing:
        certificates:
          - FireOpsCalc_Distribution_2025
        provisioning_profiles:
          - FireOpsCalcApp_AppStore

      # Optional: if you want it uploaded to TestFlight automatically
      publishing:
        app_store_connect:
          api_key: FireCalc

    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx cap sync ios

      - name: Clean build
        script: |
          xcodebuild clean -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release

      - name: Build Xcode archive
        script: |
          xcodebuild -workspace "$WORKSPACE" \
          -scheme "$SCHEME" \
          -configuration Release \
          -archivePath "$ARCHIVE_PATH" \
          -allowProvisioningUpdates \
          DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
          PRODUCT_BUNDLE_IDENTIFIER="$PRODUCT_BUNDLE_IDENTIFIER" \
          CODE_SIGN_STYLE=Manual \
          CODE_SIGN_IDENTITY="Apple Distribution"

      - name: Export IPA (sign & upload)
        script: |
          xcodebuild -exportArchive \
          -archivePath "$ARCHIVE_PATH" \
          -exportOptionsPlist ios/App/AppStoreExportOptions.plist \
          -exportPath "$IPA_EXPORT_DIR" \
          -allowProvisioningUpdates

    artifacts:
      - $IPA_EXPORT_DIR/*.ipa
      - $IPA_EXPORT_DIR/*.dSYM.zip
      - $IPA_EXPORT_DIR/*.log
