workflows:
  ios-capacitor:
    name: iOS Capacitor → TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      node: 20
      xcode: latest
      cocoapods: default
      vars:
        APP_IDENTIFIER: com.fireopscalc.app
        APP_NAME: FireOps Calc
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSU
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIV

    scripts:
      - name: Install deps
        script: |
          echo "Node:" && node -v
          if ! npm ci; then
            echo "npm ci failed, trying legacy peer deps"
            npm install --legacy-peer-deps
          fi

      - name: Build web to dist/
        script: |
          # Try your app's build script; if none, fall back to copying root index.html
          npm run build || (mkdir -p dist && cp index.html dist/index.html)
          test -f dist/index.html || (echo "dist/index.html missing" && exit 1)

      - name: Capacitor sync (installs pods in cloud)
        script: |
          npx cap sync ios

      - name: Automatic code signing (App Store Connect API)
        script: |
          xcode-project use-profiles \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"

      - name: Build .ipa
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App" \
            --archive-path "$CM_BUILD_DIR/App.xcarchive"

      - name: Publish to TestFlight
        script: |
          IPA_PATH="$(find . -type f -name '*.ipa' | head -n 1)"
          echo "Uploading $IPA_PATH"
          app-store-connect publish \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --path "$IPA_PATH" \
            --submit-to-testflight

    artifacts:
      - "**/*.ipa"
      - "ios/App/build/**"
