- name: List schemes & pick one that exists
  script: |
    set -euo pipefail
    xcodebuild -list -json -workspace "$WORKSPACE" > schemes.json || true
    python3 - <<'PY'
    import json, os, sys
    data=json.load(open("schemes.json"))
    schemes=[]
    for k in ("workspace","project"):
        if k in data and "schemes" in data[k]:
            schemes = data[k]["schemes"] or []
            break
    print("Schemes:", schemes)
    prefer=os.environ.get("SCHEME","").strip()
    picked=""
    if prefer in schemes:
        picked=prefer
    elif any("App"==s for s in schemes):
        picked="App"
    elif any("App" in s for s in schemes):
        picked=[s for s in schemes if "App" in s][0]
    elif schemes:
        picked=schemes[0]
    if not picked:
        print("ERROR: No shared schemes found. Share the scheme in Xcode (Manage Schemes… → Shared) so it’s committed under xcshareddata.", file=sys.stderr)
        sys.exit(2)
    open("picked_scheme.txt","w").write(picked)
    print("Picked scheme:", picked)
    PY

- name: Build Xcode archive (print full errors)
  script: |
    set -euo pipefail
    export PICKED_SCHEME="$(cat picked_scheme.txt)"
    echo "Archiving with scheme: $PICKED_SCHEME"
    # Show key build settings to catch mismatches
    xcodebuild -showBuildSettings \
      -workspace "$WORKSPACE" \
      -scheme "$PICKED_SCHEME" \
      -configuration Release | egrep -i "PRODUCT_BUNDLE_IDENTIFIER|DEVELOPMENT_TEAM|CODE_SIGN_STYLE|PROVISIONING_PROFILE" || true

    # IMPORTANT: don't pipe through xcpretty so we can see the real error
    xcodebuild \
      -workspace "$WORKSPACE" \
      -scheme "$PICKED_SCHEME" \
      -configuration Release \
      -archivePath "$ARCHIVE_PATH" \
      -destination "generic/platform=iOS" \
      -allowProvisioningUpdates \
      CODE_SIGN_STYLE=Automatic \
      DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
      clean archive

    test -d "$ARCHIVE_PATH" || (echo "Archive not created at $ARCHIVE_PATH" && exit 1)
