workflows:
  ios_release:
    name: "iOS App Store build"
    max_build_duration: 60

    environment:
      groups:
        - appstore_connect       # your env group in Codemagic
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"

    scripts:
      - name: Install signing assets (p12 + provisioning profile)
        script: |
          set -e

          echo "Checking env vars…"
          if [ -z "$IOS_CERTIFICATE_P12_BASE64" ]; then
            echo "❌ IOS_CERTIFICATE_P12_BASE64 is EMPTY"
            exit 1
          fi

          if [ -z "$IOS_PROVISION_PROFILE_BASE64" ]; then
            echo "❌ IOS_PROVISION_PROFILE_BASE64 is EMPTY"
            exit 1
          fi

          if [ -z "$P12_PASSWORD" ]; then
            echo "❌ P12_PASSWORD is EMPTY"
            exit 1
          fi

          echo "Decoding certificate and provisioning profile…"
          echo "$IOS_CERTIFICATE_P12_BASE64" | base64 --decode > certificate.p12
          echo "$IOS_PROVISION_PROFILE_BASE64" | base64 --decode > provisioning.mobileprovision

          echo "Creating and unlocking temporary keychain…"
          KEYCHAIN_PATH="$HOME/Library/Keychains/build.keychain-db"

          # Create a new keychain with empty password
          security create-keychain -p "" "$KEYCHAIN_PATH"

          # Make it the default keychain
          security default-keychain -s "$KEYCHAIN_PATH"

          # Unlock the keychain and keep it unlocked for a while
          security unlock-keychain -p "" "$KEYCHAIN_PATH"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"

          echo "Importing certificate into keychain…"
          security import certificate.p12 \
            -k "$KEYCHAIN_PATH" \
            -P "$P12_PASSWORD" \
            -A -t cert -f pkcs12 \
            -T /usr/bin/codesign \
            -T /usr/bin/security

          echo "Listing keychains to confirm..."
          security list-keychains

          echo "Installing provisioning profile…"
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp provisioning.mobileprovision \
            ~/Library/MobileDevice/Provisioning\ Profiles/app.mobileprovision

          echo "✅ Signing assets installed"

      - name: Build IPA
        script: |
          set -e

          echo "🔎 Debug: where are we?"
          pwd
          echo "🔎 Debug: listing ios/App:"
          ls -R ios/App || true

          echo "Preparing export_options.plist for xcode-project…"
          if [ -f "export_options.plist" ]; then
            echo "Found export_options.plist in repo root, copying to \$HOME…"
            cp "export_options.plist" "$HOME/export_options.plist"
          else
            echo "❌ export_options.plist not found in repo root"
            echo "Contents of current directory:"
            ls -R .
            exit 1
          fi

          echo "🔎 Debug: listing schemes in project..."
          xcodebuild -project "$XCODE_PROJECT" -list || true

          echo "🔎 Debug: showing build settings for scheme '$XCODE_SCHEME'..."
          xcodebuild -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" -showBuildSettings

          echo "📦 Building signed IPA with xcode-project (project, not workspace)…"
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - $CM_BUILD_DIR/**/*.ipa
      - $CM_BUILD_DIR/App.xcarchive/**
