workflows:
  ios_release:
    name: FireOpsCalc iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      # Create this variable group in Codemagic and add:
      #  - APP_STORE_CONNECT_PRIVATE_KEY  (entire .p8 contents)
      #  - APP_STORE_CONNECT_KEY_IDENTIFIER (e.g., HG4YL5BFZ or NMM68D7U4T3B)
      #  - APP_STORE_CONNECT_ISSUER_ID     (your issuer UUID)
      groups:
        - appstore_connect
      xcode: 16.4
      cocoapods: default
      node: 20.11.1
      vars:
        PRODUCT_BUNDLE_IDENTIFIER: "com.fireopscalc.app"
        DEVELOPMENT_TEAM: "QZ55W58398"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        ARCHIVE_PATH: "$CM_BUILD_DIR/build/App.xcarchive"
        IPA_EXPORT_DIR: "$CM_BUILD_DIR/Export"
        IPA_NAME: "FireOpsCalc.ipa"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.fireopscalc.app"

    triggering:
      events: [push, tag]
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      - name: Install JS deps & sync Capacitor
        script: |
          if [ -f package.json ]; then
            npm ci || npm install
          fi
          npx cap sync ios || true

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install --repo-update
          cd -

      - name: Fetch signing (Developer Portal integration)
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$PRODUCT_BUNDLE_IDENTIFIER" --type IOS_APP_STORE --create || true
          keychain add-certificates || true

      - name: Resolve matching App Store provisioning profile (persist to $CM_ENV)
        script: |
          set -euo pipefail
          BUNDLE_ID="$PRODUCT_BUNDLE_IDENTIFIER"
          TEAM_ID="$DEVELOPMENT_TEAM"
          PROFILE_UUID=""
          PROFILE_NAME=""

          PROFILE_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          echo "Scanning profiles in: $PROFILE_DIR"
          shopt -s nullglob
          for mp in "$PROFILE_DIR"/*.mobileprovision; do
            plist="$(mktemp)"
            security cms -D -i "$mp" > "$plist" 2>/dev/null || continue

            app_id=$(/usr/libexec/PlistBuddy -c "Print :Entitlements:application-identifier" "$plist" 2>/dev/null || true)
            name=$(/usr/libexec/PlistBuddy -c "Print :Name" "$plist" 2>/dev/null || true)
            uuid=$(/usr/libexec/PlistBuddy -c "Print :UUID" "$plist" 2>/dev/null || true)
            method=$(/usr/libexec/PlistBuddy -c "Print :ProvisionsAllDevices" "$plist" 2>/dev/null || true)
            # App Store profiles have NO ProvisionsAllDevices and NO ProvisionedDevices (we don't strictly need to check)

            if [[ "$app_id" == "${TEAM_ID}.${BUNDLE_ID}" ]]; then
              PROFILE_UUID="$uuid"
              PROFILE_NAME="$name"
              echo "Matched profile: $name  (UUID: $uuid)"
              rm -f "$plist"
              break
            fi
            rm -f "$plist"
          done
          shopt -u nullglob

          if [[ -z "$PROFILE_UUID" ]]; then
            echo "ERROR: No provisioning profile found matching ${TEAM_ID}.${BUNDLE_ID}"
            ls -la "$PROFILE_DIR" || true
            exit 1
          fi

          # Persist for subsequent steps:
          echo "PROFILE_UUID=$PROFILE_UUID" >> $CM_ENV
          echo "PROFILE_NAME=$PROFILE_NAME" >> $CM_ENV
          echo "Resolved profile => NAME: $PROFILE_NAME | UUID: $PROFILE_UUID"

      - name: Build Xcode archive (force distribution signing)
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            -destination 'generic/platform=iOS' \
            clean archive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$PRODUCT_BUNDLE_IDENTIFIER" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE="$PROFILE_UUID"

      - name: Create exportOptions.plist (manual + profile map)
        script: |
          cat > exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>destination</key><string>export</string>
            <key>uploadSymbols</key><true/>
            <key>compileBitcode</key><false/>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.fireopscalc.app</key><string>${PROFILE_NAME}</string>
            </dict>
          </dict>
          </plist>
          EOF
          echo "exportOptions.plist created with profile ${PROFILE_NAME}"

      - name: Export IPA
        script: |
          mkdir -p "$IPA_EXPORT_DIR"
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportPath "$IPA_EXPORT_DIR" \
            -exportOptionsPlist exportOptions.plist
          if [ -f "$IPA_EXPORT_DIR/$XCODE_SCHEME.ipa" ]; then
            mv "$IPA_EXPORT_DIR/$XCODE_SCHEME.ipa" "$IPA_EXPORT_DIR/$IPA_NAME"
          fi
          ls -la "$IPA_EXPORT_DIR"

    artifacts:
      - "$IPA_EXPORT_DIR/*.ipa"
      - "$ARCHIVE_PATH"
      - "exportOptions.plist"
      - "**/dSYMs/**"

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
