workflows:
  ios_release:
    name: iOS Release (Manual signing via p12 + mobileprovision)
    instance_type: mac_mini_m2
    max_build_duration: 60

    integrations:
      app_store_connect: FireCalc

    environment:
      xcode: 16.4
      cocoapods: default
      groups:
        - appstore_connect
      vars:
        WORKSPACE: "ios/App/App.xcworkspace"
        SCHEME: "App"
        ARCHIVE_PATH: "/Users/builder/clone/build/App.xcarchive"
        EXPORT_DIR: "/Users/builder/clone/Export"
        BUNDLE_ID: "com.fireopscalc.app"
        DEV_TEAM: "QZ55W58398"

    scripts:
      - name: Install signing assets (p12 + provisioning profile)
        script: |
          set -eo pipefail
          : "${IOS_CERTIFICATE_P12_BASE64:?Missing IOS_CERTIFICATE_P12_BASE64}"
          : "${IOS_CERTIFICATE_PASSWORD:?Missing IOS_CERTIFICATE_PASSWORD}"
          : "${IOS_PROVISION_PROFILE_BASE64:?Missing IOS_PROVISION_PROFILE_BASE64}"

          echo "$IOS_CERTIFICATE_P12_BASE64" | base64 --decode > dist.p12
          echo "$IOS_PROVISION_PROFILE_BASE64" | base64 --decode > profile.mobileprovision

          KEYCHAIN_PATH="$HOME/Library/Keychains/codemagic-signing.keychain-db"
          security create-keychain -p "" "$KEYCHAIN_PATH"
          security set-keychain-settings "$KEYCHAIN_PATH"
          security unlock-keychain -p "" "$KEYCHAIN_PATH"
          security import dist.p12 -k "$KEYCHAIN_PATH" -P "$IOS_CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security list-keychains -s "$KEYCHAIN_PATH"
          security default-keychain -s "$KEYCHAIN_PATH"

          PROFILES_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILES_DIR"
          UUID=$(/usr/bin/grep -a -A1 UUID profile.mobileprovision | /usr/bin/sed -n 's/.*<string>\(.*\)<\/string>.*/\1/p' | /usr/bin/head -n1)
          cp profile.mobileprovision "$PROFILES_DIR/$UUID.mobileprovision"
          echo "Installed mobileprovision UUID: $UUID"

      - name: Ensure Manual signing for the app target only
        script: |
          set -eo pipefail
          PBX="ios/App/App.xcodeproj/project.pbxproj"
          /usr/bin/sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' "$PBX"
          /usr/bin/sed -i '' 's/ProvisioningStyle = Automatic;/ProvisioningStyle = Manual;/g' "$PBX"
          /usr/bin/sed -i '' 's/PROVISIONING_PROFILE_SPECIFIER = [^;]*;/PROVISIONING_PROFILE_SPECIFIER = "";/g' "$PBX"
          /usr/bin/sed -i '' 's/PROVISIONING_PROFILE = [^;]*;/PROVISIONING_PROFILE = "";/g' "$PBX"

      - name: Install CocoaPods
        script: |
          set -eo pipefail
          cd ios/App
          pod install --repo-update

      - name: Build Xcode archive (Release, Manual signing)
        script: |
          set -eo pipefail
          xcodebuild -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            -destination generic/platform=iOS \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="$DEV_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            clean archive

      - name: Export signed IPA (App Store)
        script: |
          set -eo pipefail
          mkdir -p "$EXPORT_DIR"
          PROFILE_NAME=$(/usr/bin/grep -a -A1 "<key>Name</key>" profile.mobileprovision | /usr/bin/sed -n 's/.*<string>\(.*\)<\/string>.*/\1/p' | /usr/bin/head -n1)
          : "${PROFILE_NAME:=AppStoreProfile}"

          cat > exportOptions.plist <<PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
            <dict>
              <key>method</key><string>app-store</string>
              <key>destination</key><string>export</string>
              <key>compileBitcode</key><false/>
              <key>stripSwiftSymbols</key><true/>
              <key>signingStyle</key><string>manual</string>
              <key>provisioningProfiles</key>
              <dict>
                <key>${BUNDLE_ID}</key><string>${PROFILE_NAME}</string>
              </dict>
            </dict>
          </plist>
          PLIST

          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportPath "$EXPORT_DIR" \
            -exportOptionsPlist exportOptions.plist

    artifacts:
      - /Users/builder/clone/Export/*.ipa
      - /Users/builder/clone/build/*.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - External Testers
