workflows:
  ios_release:
    name: iOS Release (App Store / TestFlight)
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      xcode: 16.4
      node: 20
      cocoapods: default
      vars:
        IOS_WORKSPACE: ios/App/App.xcworkspace
        IOS_SCHEME: App
        BUNDLE_ID: com.fireopscalc.app
        DEVELOPMENT_TEAM: QZ55W58398

    cache:
      cache_paths:
        - ~/.npm
        - ~/.cocoapods
        - ios/App/Pods

    # <-- This must be a STRING and only inside the workflow
    integrations:
      app_store_connect: FireOpsCalc_iOS-KEY

    scripts:
      - name: Show tool versions
        script: |
          node -v
          npm -v
          pod --version
          xcodebuild -version

      - name: Install dependencies
        script: npm ci

      - name: Sync Capacitor iOS
        script: npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod repo update
          pod install --verbose

      - name: Build iOS archive (Release) with Automatic signing
        script: |
          ARCHIVE_PATH="${CM_BUILD_DIR:-$PWD/build}/App.xcarchive"
          xcodebuild -workspace "$IOS_WORKSPACE" \
            -scheme "$IOS_SCHEME" \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath "$ARCHIVE_PATH" \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            clean archive | xcpretty

      - name: Export IPA (App Store)
        script: |
          ARCHIVE_PATH="${CM_BUILD_DIR:-$PWD/build}/App.xcarchive"
          EXPORT_DIR="${CM_BUILD_DIR:-$PWD/build}/Export"
          mkdir -p "$EXPORT_DIR"

          cat > ExportOptions.plist <<PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>automatic</string>
            <key>stripSwiftSymbols</key><true/>
          </dict>
          </plist>
          PLIST

          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath "$EXPORT_DIR" | xcpretty
          ls -la "$EXPORT_DIR"

    artifacts:
      - build/Export/*.ipa
      - $CM_BUILD_DIR/Export/*.ipa
      - $CM_BUILD_DIR/App.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
