workflows:
  android-release:
    name: FireOps Calc – Android Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      java: 21
      node: 18
      vars:
        ANDROID_APP_ID: "com.fireopscalc.app"
        ANDROID_APP_NAME: "FireOps Calc"
      # This references the keystore you added in Codemagic:
      # Code signing → Android keystores → FireOpsCalcReleaseKey
      android_signing:
        - FireOpsCalcReleaseKey

    scripts:
      - name: Show versions
        script: |
          node -v
          npm -v
          java -version

      - name: Install Node dependencies
        script: |
          npm install

      - name: Sync Capacitor Android
        script: |
          npx cap sync android

      - name: Build signed Android App Bundle
        script: |
          cd android
          ./gradlew clean bundleRelease \
            -Pandroid.injected.signing.store.file=$CM_KEYSTORE_PATH \
            -Pandroid.injected.signing.store.password=$CM_KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$CM_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$CM_KEY_PASSWORD

    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - "your-email@example.com"   # <- change to your email
        notify:
          success: true
          failure: true


  ios_release:
    name: FireOps Calc – iOS Release
    max_build_duration: 90
    instance_type: mac_mini_m2

    environment:
      xcode: 16.0
      node: 18
      vars:
        IOS_APP_ID: "com.fireopscalc.app"
        IOS_APP_NAME: "FireOps Calc"

    scripts:
      - name: Show versions
        script: |
          node -v
          npm -v
          xcodebuild -version

      - name: Install Node dependencies
        script: |
          npm install

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Build iOS archive
        script: |
          cd ios/App
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath $PWD/build/App.xcarchive \
            archive

    artifacts:
      - ios/App/build/**/*.ipa
      - ios/App/build/**/*.xcarchive
