workflows:
  ios_release:
    name: iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60

    integrations:
      app_store_connect: FireCalc

    environment:
      xcode: 16.4
      ios_signing:
        provisioning_profiles:
          - FireOpsCalcprofile
      vars:
        DEVELOPMENT_TEAM: QZ55W58398
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App
        ARCHIVE_PATH: $CM_BUILD_DIR/build/App.xcarchive
        EXPORT_DIR: $CM_BUILD_DIR/Export

    cache:
      cache_paths:
        - ~/.npm
        - ~/Library/Caches/CocoaPods
        - ios/Pods -> ios/Podfile.lock
        - ios/App/Pods -> ios/App/Podfile.lock

    scripts:
      - name: Install Node deps
        script: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Capacitor iOS sync
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          if [ -f "ios/App/Podfile" ]; then
            cd ios/App
            pod install
          elif [ -f "ios/Podfile" ]; then
            cd ios
            pod install
          else
            echo "No Podfile found"
          fi

      - name: Inject signing profiles
        script: |
          xcode-project use-profiles

      - name: 🔍 DIAGNOSTIC — Dump Signing Settings
        script: |
          echo "=== SIGNING SETTINGS DUMP START ==="
          xcode-project show-build-settings | grep -E "PROVISIONING_PROFILE|PROVISIONING_PROFILE_SPECIFIER|DEVELOPMENT_TEAM|CODE_SIGN" || true
          echo "=== SIGNING SETTINGS DUMP END ==="
          exit 1   # ❌ Force fail so we can read the dump

    artifacts:
      - $CM_BUILD_DIR/build/*.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: false
