workflows:
  ios_release:
    name: FireOpsCalc iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60

    # needed so publishing: app_store_connect works
    integrations:
      app_store_connect: FireCalc

    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true

    environment:
      xcode: 16.4
      cocoapods: default
      node: 20.11.1
      vars:
        WORKSPACE: "ios/App/App.xcworkspace"
        SCHEME: "App"
        BUNDLE_ID: "com.fireopscalc.app"
        ARCHIVE_PATH: "/Users/builder/clone/build/App.xcarchive"
        EXPORT_DIR: "/Users/builder/clone/Export"
        IPA_NAME: "FireOpsCalc.ipa"

      # 👇 this is what makes CM actually MOUNT the items you showed in your screenshots
      ios_signing:
        certificates:
          # fix the earlier typo "FireCalcCertiicate"
          # use the name as it appears in Codemagic UI
          - FireOpsCalcCertificate
        provisioning_profiles:
          # you had both of these in your logs/screens:
          - FireOpsCalcApp_AppStore
          - FireOpsCalcprofile

    scripts:
      - name: 1) Install Node deps & build web
        script: |
          set -e
          if [ -f package.json ]; then
            if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
              npm ci || npm install
            else
              npm install
            fi
            npm run build --if-present
          else
            echo "No package.json, skipping web build."
          fi

      - name: 2) Capacitor sync iOS
        script: |
          set -e
          if [ -f capacitor.config.ts ] || [ -f capacitor.config.json ] || [ -f capacitor.config.js ]; then
            npx cap sync ios
          else
            echo "No capacitor config, skipping npx cap sync ios"
          fi
          echo "=== ios/App/App after sync ==="
          ls -la ios/App/App || true

      - name: 3) Install CocoaPods
        script: |
          set -e
          cd ios/App
          pod install --repo-update || pod install
          cd ../..

      - name: 4) Try to fetch from App Store Connect (POSitional syntax!) and show what CM mounted
        script: |
          # don't "set -e" here, we want to CONTINUE even if fetch fails
          echo "=== 4a) Try: app-store-connect fetch-signing-files (App Store) ==="
          app-store-connect fetch-signing-files com.fireopscalc.app \
            --type IOS_APP_STORE \
            --create \
            || echo "⚠️ fetch (IOS_APP_STORE) failed — will keep going"

          echo "=== 4b) Try: app-store-connect fetch-signing-files (Development) ==="
          app-store-connect fetch-signing-files com.fireopscalc.app \
            --type IOS_APP_DEVELOPMENT \
            --create \
            || echo "⚠️ fetch (IOS_APP_DEVELOPMENT) failed — will keep going"

          echo "=== 4c) Import any certs CM mounted ==="
          keychain add-certificates || echo "⚠️ keychain add-certificates had nothing to import"

          echo "=== 4d) Apply to Xcode project (may fail if nothing was mounted) ==="
          xcode-project use-profiles || echo "⚠️ xcode-project use-profiles failed (usually means no profiles)"

          echo "=== 4e) What did CM actually mount? ==="
          echo "CM_PROVISIONING_PROFILES_DIR=$CM_PROVISIONING_PROFILES_DIR"
          if [ -n "$CM_PROVISIONING_PROFILES_DIR" ] && [ -d "$CM_PROVISIONING_PROFILES_DIR" ]; then
            ls -R "$CM_PROVISIONING_PROFILES_DIR" || true
          else
            echo "❌ CM_PROVISIONING_PROFILES_DIR is empty — check codemagic UI code signing NAMES"
          fi

          echo "=== 4f) List profiles from ASC (diagnostic) ==="
          app-store-connect profiles --json || true

          echo "=== 4g) List certs from ASC (diagnostic) ==="
          app-store-connect certificates --json || true

      - name: 5) Create ExportOptions.plist (App Store Connect)
        script: |
          set -e
          EXPORT_PLIST="/Users/builder/export_options.plist"
          rm -f "$EXPORT_PLIST"
          /usr/bin/plutil -create xml1 "$EXPORT_PLIST"
          /usr/libexec/PlistBuddy -c "Add :method string app-store-connect" "$EXPORT_PLIST"
          /usr/libexec/PlistBuddy -c "Add :teamID string QZ55W58398" "$EXPORT_PLIST"
          /usr/libexec/PlistBuddy -c "Add :uploadBitcode bool false" "$EXPORT_PLIST"
          /usr/libexec/PlistBuddy -c "Add :compileBitcode bool false" "$EXPORT_PLIST"
          echo "=== ExportOptions.plist ==="
          /usr/libexec/PlistBuddy -c "Print" "$EXPORT_PLIST"

      - name: 6) Archive (stop here if no profile)
        script: |
          set -e
          echo "=== xcodebuild archive starting ==="
          xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath "$ARCHIVE_PATH" \
            archive \
            | xcpretty

          if [ ! -d "$ARCHIVE_PATH" ]; then
            echo "❌ Archive not found at $ARCHIVE_PATH"
            ls -R /Users/builder/clone/build || true
            # hard fail so we don't get the fake 'no .ipa' error later
            exit 1
          fi
          echo "✅ Archive created at $ARCHIVE_PATH"

      - name: 7) Export IPA
        script: |
          set -e
          mkdir -p "$EXPORT_DIR"
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist /Users/builder/export_options.plist \
            -exportPath "$EXPORT_DIR" \
            | xcpretty

          IPA_PATH="$(ls -1t "$EXPORT_DIR"/*.ipa 2>/dev/null | head -n 1)"
          if [ -z "$IPA_PATH" ]; then
            echo "❌ No IPA created"
            ls -la "$EXPORT_DIR" || true
            exit 1
          fi

          mv -f "$IPA_PATH" "$EXPORT_DIR/$IPA_NAME"
          echo "✅ IPA at $EXPORT_DIR/$IPA_NAME"

    artifacts:
      - "$EXPORT_DIR/$IPA_NAME"

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
