# codemagic.yaml
# iOS release build with **automatic signing** and App Store Connect upload.
# Requires a Codemagic variable group named `app_store_connect` containing:
#   - APP_STORE_CONNECT_PRIVATE_KEY   (paste the full .p8 contents)
#   - APP_STORE_CONNECT_KEY_IDENTIFIER (e.g. 82567339RS)
#   - APP_STORE_CONNECT_ISSUER_ID      (e.g. a786600e-e10a-42b2-a2bf-443a1da2554b)

workflows:
  ios_release:
    name: iOS Release (ASC upload)
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      groups:
        - app_store_connect               # <- provides the three ASC vars above
      ios_signing:
        distribution_type: app_store      # use App Store distribution with automatic signing
        bundle_identifier: com.fireopscalc.app
      vars:
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App
        DEVELOPMENT_TEAM: QZ55W58398
        APP_NAME: FireOps Calc

    scripts:
      - name: Preflight — resolve & verify App Store Connect vars
        script: |
          set -euo pipefail
          for v in APP_STORE_CONNECT_PRIVATE_KEY APP_STORE_CONNECT_KEY_IDENTIFIER APP_STORE_CONNECT_ISSUER_ID; do
            if [ -z "${!v:-}" ]; then
              echo "❌ Missing required env var: $v"
              exit 1
            fi
          done
          echo "✅ App Store Connect variables present."

      - name: Install CocoaPods
        script: |
          set -euo pipefail
          cd ios
          pod install
          cd -

      - name: Generate exportOptions.plist (App Store)
        script: |
          set -euo pipefail
          cat > ios/exportOptions.plist <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>destination</key><string>export</string>
            <key>compileBitcode</key><false/>
            <key>signingStyle</key><string>automatic</string>
            <key>uploadSymbols</key><true/>
            <key>stripSwiftSymbols</key><true/>
          </dict>
          </plist>
          PLIST

      - name: Archive
        script: |
          set -euxo pipefail
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -allowProvisioningUpdates \
            PRODUCT_BUNDLE_IDENTIFIER=com.fireopscalc.app \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            archive -archivePath "$CM_BUILD_DIR/App.xcarchive"

      - name: Export IPA
        script: |
          set -euxo pipefail
          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportPath "$CM_BUILD_DIR/ipa" \
            -exportOptionsPlist ios/exportOptions.plist \
            -allowProvisioningUpdates
          ls -lah "$CM_BUILD_DIR/ipa"

    artifacts:
      - $CM_BUILD_DIR/ipa/*.ipa
      - $CM_BUILD_DIR/App.xcarchive

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY     # .p8 content from ASC
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER   # e.g. 82567339RS
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID     # e.g. a786600e-e10a-42b2-a2bf-443a1da2554b
        submit_to_testflight: true                   # upload to TestFlight after build
        # Optional:
        # beta_groups: ["Internal Testing"]
        # expire_build_submitted_for_review: false
