workflows:
  ios_release:
    name: FireOpsCalc iOS Release (App Store)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: 16.4
      cocoapods: default
      node: 20.11.1

      vars:
        PRODUCT_BUNDLE_IDENTIFIER: "com.fireopscalc.app"
        DEVELOPMENT_TEAM: "QZ55W58398"
        WORKSPACE: "ios/App/App.xcworkspace"
        SCHEME: "App"

        ARCHIVE_PATH: "/Users/builder/clone/build/App.xcarchive"
        DERIVED_DATA: "/Users/builder/clone/DerivedData"
        IPA_EXPORT_DIR: "/Users/builder/clone/Export"
        IPA_NAME: "FireOpsCalc.ipa"

        PUBLISH_TO_TESTFLIGHT: "true"

      ios_signing:
        certificates:
          - FireOpsCalc_Distribution_2025
        provisioning_profiles:
          - FireOpsCalc_AppStore_Profile

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build iOS release
        script: |
          cd ios
          pod install
          cd ..
          xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            clean archive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$PRODUCT_BUNDLE_IDENTIFIER" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution"

      - name: Export IPA (sign & verify)
        script: |
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist ios/App/exportOptions.plist \
            -exportPath "$IPA_EXPORT_DIR"

    artifacts:
      - build/**/*.ipa
      - build/**/*.dSYM.zip
      - build/**/*.app
