workflows:
  ios-app-store:
    name: iOS App Store build
    instance_type: mac_mini_m1
    max_build_duration: 60

    environment:
      # Vars you can tweak for your project structure
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"   # <- update if different
        XCODE_SCHEME: "App"                          # <- update if different
        CONFIGURATION: "Release"
        EXPORT_METHOD: "app-store"

      # This must match the group name you created in Codemagic
      groups:
        - appstore_connect

    scripts:
      - name: Install signing assets (p12 + provisioning profile)
        script: |
          #!/bin/bash
          set -eo pipefail

          echo "🔐 Installing iOS signing assets..."

          # --- Sanity checks for env vars ---
          if [ -z "${IOS_CERTIFICATE_P12_BASE64:-}" ]; then
            echo "❌ IOS_CERTIFICATE_P12_BASE64 is not set"
            exit 1
          fi

          if [ -z "${IOS_PROVISION_PROFILE_BASE64:-}" ]; then
            echo "❌ IOS_PROVISION_PROFILE_BASE64 is not set"
            exit 1
          fi

          if [ -z "${P12_PASSWORD:-}" ]; then
            echo "❌ P12_PASSWORD is not set"
            exit 1
          fi

          # --- Decode certificate & profile ---
          CERT_PATH="/tmp/certificate.p12"
          PROFILE_PATH="/tmp/profile.mobileprovision"

          echo "📄 Decoding p12 certificate..."
          echo "$IOS_CERTIFICATE_P12_BASE64" | base64 --decode > "$CERT_PATH"

          echo "📄 Decoding provisioning profile..."
          echo "$IOS_PROVISION_PROFILE_BASE64" | base64 --decode > "$PROFILE_PATH"

          # --- Install provisioning profile ---
          echo "📥 Installing provisioning profile..."
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          cp "$PROFILE_PATH" "$HOME/Library/MobileDevice/Provisioning Profiles/fireopscalc_profile.mobileprovision"

          # --- Create & use build keychain ---
          KEYCHAIN_NAME="build.keychain"
          KEYCHAIN_PWD=""

          echo "🔑 Creating keychain..."
          security create-keychain -p "$KEYCHAIN_PWD" "$KEYCHAIN_NAME"
          security import "$CERT_PATH" -k "$KEYCHAIN_NAME" -P "$P12_PASSWORD" -A

          echo "🔓 Configuring keychain..."
          security list-keychains -s "$KEYCHAIN_NAME"
          security default-keychain -s "$KEYCHAIN_NAME"
          security unlock-keychain -p "$KEYCHAIN_PWD" "$KEYCHAIN_NAME"
          security set-keychain-settings "$KEYCHAIN_NAME"

          echo "✅ iOS signing assets installed."

      - name: Build Xcode archive
        script: |
          #!/bin/bash
          set -eo pipefail

          echo "🏗  Building Xcode archive..."
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration "$CONFIGURATION" \
            -sdk iphoneos \
            -archivePath "$CM_BUILD_DIR/ios_archive.xcarchive" \
            clean archive

      - name: Export .ipa
        script: |
          #!/bin/bash
          set -eo pipefail

          echo "📦 Exporting IPA..."
          EXPORT_OPTIONS_PLIST="$CM_BUILD_DIR/exportOptions.plist"

          cat <<EOF > "$EXPORT_OPTIONS_PLIST"
          {
            "method": "$EXPORT_METHOD",
            "compileBitcode": false,
            "signingStyle": "manual",
            "stripSwiftSymbols": true
          }
          EOF

          xcodebuild \
            -exportArchive \
            -archivePath "$CM_BUILD_DIR/ios_archive.xcarchive" \
            -exportOptionsPlist "$EXPORT_OPTIONS_PLIST" \
            -exportPath "$CM_BUILD_DIR/ipa"

    artifacts:
      - "$CM_BUILD_DIR/ipa/*.ipa"

    publishing:
      app_store_connect:
        # These should also be in your appstore_connect group:
        # APP_STORE_CONNECT_ISSUER_ID
        # APP_STORE_CONNECT_KEY_IDENTIFIER
        # APP_STORE_CONNECT_PRIVATE_KEY
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true
        submit_to_app_store: false
