workflows:
  android-release:
    name: FireOps Calc – Android Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      java: 21
      vars:
        ANDROID_APP_ID: "com.fireopscalc.app"
        ANDROID_APP_NAME: "FireOps Calc"
      android_signing:
        # This must match the name shown under “Available keystores”
        - FireOpsCalcReleaseKey

    scripts:
      - name: Install Node dependencies
        script: |
          npm install

      - name: Build signed Android App Bundle
        script: |
          cd android
          ./gradlew clean bundleRelease \
            -Pandroid.injected.signing.store.file=$CM_KEYSTORE_PATH \
            -Pandroid.injected.signing.store.password=$CM_KEYSTORE_PASSWORD \
            -Pandroid.injected.signing.key.alias=$CM_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$CM_KEY_PASSWORD

    artifacts:
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - "you@example.com"   # change to your email
        notify:
          success: true
          failure: true
