workflows:
  ios_release:
    name: FireOpsCalc iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      # Create this variable group in Codemagic and add:
      #  - APP_STORE_CONNECT_PRIVATE_KEY  (entire .p8 contents)
      #  - APP_STORE_CONNECT_KEY_IDENTIFIER (e.g., HG4YL5BFZ)
      #  - APP_STORE_CONNECT_ISSUER_ID     (your issuer UUID)
      groups:
        - appstore_connect
      xcode: 16.4
      cocoapods: default
      node: 20.11.1
      vars:
        PRODUCT_BUNDLE_IDENTIFIER: "com.fireopscalc.app"
        DEVELOPMENT_TEAM: "QZ55W58398"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        ARCHIVE_PATH: "$CM_BUILD_DIR/build/App.xcarchive"
        IPA_EXPORT_DIR: "$CM_BUILD_DIR/Export"
        IPA_NAME: "FireOpsCalc.ipa"
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.fireopscalc.app"

    triggering:
      events: [push, tag]
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      - name: Install JS deps & sync Capacitor
        script: |
          if [ -f package.json ]; then
            npm ci || npm install
          fi
          npx cap sync ios || true

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install --repo-update
          cd -

      - name: Fetch signing (Developer Portal integration)
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$PRODUCT_BUNDLE_IDENTIFIER" --type IOS_APP_STORE --create || true
          keychain add-certificates || true

      - name: Choose App Store provisioning profile
        script: |
          # Use the exact profile name shown in Codemagic → Teams → Provisioning profiles
          export PROFILE_NAME="FireOpsCalcprofile"
          # If you prefer the other one, comment the line above and uncomment the next line:
          # export PROFILE_NAME="FireOpsCalcApp_AppStore"
          echo "Using provisioning profile: $PROFILE_NAME"

      - name: Build Xcode archive (force distribution signing)
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            -destination 'generic/platform=iOS' \
            clean archive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$PRODUCT_BUNDLE_IDENTIFIER" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_NAME"

      - name: Create exportOptions.plist (manual + profile map)
        script: |
          cat > exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>destination</key><string>export</string>
            <key>uploadSymbols</key><true/>
            <key>compileBitcode</key><false/>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.fireopscalc.app</key><string>${PROFILE_NAME}</string>
            </dict>
          </dict>
          </plist>
          EOF
          echo "exportOptions.plist created with profile ${PROFILE_NAME}"

      - name: Export IPA
        script: |
          mkdir -p "$IPA_EXPORT_DIR"
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportPath "$IPA_EXPORT_DIR" \
            -exportOptionsPlist exportOptions.plist
          if [ -f "$IPA_EXPORT_DIR/$XCODE_SCHEME.ipa" ]; then
            mv "$IPA_EXPORT_DIR/$XCODE_SCHEME.ipa" "$IPA_EXPORT_DIR/$IPA_NAME"
          fi
          ls -la "$IPA_EXPORT_DIR"

    artifacts:
      - "$IPA_EXPORT_DIR/*.ipa"
      - "$ARCHIVE_PATH"
      - "exportOptions.plist"
      - "**/dSYMs/**"

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
