workflows:
  ios_release:
    name: iOS App Store Release
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      xcode: 16.4
      cocoapods: default
      node: 20.11.1
      vars:
        PRODUCT_BUNDLE_IDENTIFIER: "com.fireopscalc.app"
        DEVELOPMENT_TEAM: "QZ55W58398"
        WORKSPACE: "ios/App/App.xcworkspace"
        SCHEME: "App"
        ARCHIVE_PATH: "/Users/builder/clone/build/App.xcarchive"
        IPA_EXPORT_DIR: "/Users/builder/clone/Export"
        IPA_NAME: "FireOpsCalc.ipa"
      groups:
        - appstore_connect

    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm run build || echo "No npm build script, skipping"
          npx cap sync ios

      - name: Build iOS archive
        script: |
          xcodebuild -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$PRODUCT_BUNDLE_IDENTIFIER" \
            CODE_SIGN_STYLE=Manual \
            clean archive | xcpretty

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist ios/App/exportOptions.plist \
            -exportPath "$IPA_EXPORT_DIR" \
            | xcpretty

    artifacts:
      - $IPA_EXPORT_DIR/*.ipa
      - build/**/FireOpsCalc.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
