workflows:
  ios_release:
    name: FireOpsCalc iOS Release (ASC fetch)
    instance_type: mac_mini_m2
    max_build_duration: 60

    # Needed for publishing.auth: integration
    integrations:
      app_store_connect: FireCalc   # <— match your ASC integration name exactly

    environment:
      xcode: 16.4
      cocoapods: default
      node: 20.11.1
      vars:
        # iOS project config
        PRODUCT_BUNDLE_IDENTIFIER: "com.fireopscalc.app"
        DEVELOPMENT_TEAM: "QZ55W58398"
        WORKSPACE: "ios/App/App.xcworkspace"
        SCHEME: "App"

        # Paths
        ARCHIVE_PATH: "/Users/builder/clone/build/App.xcarchive"
        EXPORT_DIR: "/Users/builder/clone/Export"
        EXPORT_PLIST: "/Users/builder/clone/ExportOptions.plist"

        # Optional app versioning if not set in Xcode project
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"

      groups:
        - appstore_connect   # <— contains ASC KEY_IDENTIFIER / ISSUER_ID / PRIVATE_KEY

    cache:
      cache_paths:
        - ~/.npm
        - ~/.cache/CocoaPods
        - ~/Library/Caches/CocoaPods
        - ios/Pods

    scripts:
      # 1) Handle web assets robustly (works with or without "npm run build")
      - name: Install deps, stage web assets, sync iOS
        script: |
          set -euo pipefail
          npm ci || npm install

          # Try to build if a "build" script exists
          if npm run 2>/dev/null | grep -qE '(^|[[:space:]])build([[:space:]]|$)'; then
            echo "Found build script → running npm run build"
            npm run build
            WEB_OUT="dist"
          else
            echo "No build script -> looking for existing assets"
            if [ -d "dist" ]; then
              WEB_OUT="dist"
            elif [ -d "www" ]; then
              WEB_OUT="www"
            elif [ -d "public" ]; then
              echo "Using public/ as web root → copying to dist/"
              rsync -a --delete public/ dist/
              WEB_OUT="dist"
            else
              echo "No dist/www/public found → creating a minimal placeholder site"
              mkdir -p dist
              printf '%s\n' \
                '<!doctype html>' \
                '<html>' \
                '  <head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/>' \
                '    <title>FireOpsCalc</title>' \
                '    <style>body{font-family:system-ui,Arial,sans-serif;padding:24px}code{background:#f4f4f4;padding:2px 6px;border-radius:4px}</style>' \
                '  </head>' \
                '  <body>' \
                '    <h1>FireOpsCalc</h1>' \
                '    <p>Placeholder web assets for Capacitor build. Replace with your real bundle.</p>' \
                '  </body>' \
                '</html>' \
              > dist/index.html
              WEB_OUT="dist"
            fi
          fi

          echo "Web output at: $WEB_OUT"
          # Copy web to iOS project (Capacitor)
          npx cap copy ios

          # Ensure Cocoapods are installed
          cd ios/App
          pod install --repo-update
          cd -

      # 2) Fetch signing files from ASC and install them
      - name: Fetch signing files from Apple & install (ASC API)
        script: |
          set -euo pipefail
          : "${APP_STORE_CONNECT_KEY_IDENTIFIER:?Missing APP_STORE_CONNECT_KEY_IDENTIFIER}"
          : "${APP_STORE_CONNECT_ISSUER_ID:?Missing APP_STORE_CONNECT_ISSUER_ID}"
          : "${APP_STORE_CONNECT_PRIVATE_KEY:?Missing APP_STORE_CONNECT_PRIVATE_KEY}"

          keychain initialize

          # Fetch or create the App Store (distribution) signing files for our bundle id
          app-store-connect fetch-signing-files \
            --type IOS_APP_STORE \
            --bundle-id "$PRODUCT_BUNDLE_IDENTIFIER" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --create

          # Import certs into the keychain and install provisioning profiles
          keychain add-certificates
          xcode-project use-profiles

          echo "🔐 Identities in keychain:"
          security find-identity -v "$(security default-keychain | tr -d '"')" || true

      # 3) Create export options (automatic signing)
      - name: Create ExportOptions.plist (automatic)
        script: |
          set -euo pipefail
          cat > "$EXPORT_PLIST" <<'PLIST'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0"><dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>automatic</string>
            <key>stripSwiftSymbols</key><true/>
            <key>uploadSymbols</key><true/>
          </dict></plist>
          PLIST
          /usr/libexec/PlistBuddy -c "Print" "$EXPORT_PLIST" || true

      # 4) Build archive (let xcodebuild pick up codesigning from installed profiles)
      - name: Build archive
        script: |
          set -euo pipefail
          xcodebuild \
            -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            -destination "generic/platform=iOS" \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$PRODUCT_BUNDLE_IDENTIFIER" \
            MARKETING_VERSION="$MARKETING_VERSION" \
            CURRENT_PROJECT_VERSION="$CURRENT_PROJECT_VERSION" \
            clean archive

          if [ ! -d "$ARCHIVE_PATH" ]; then
            echo "❌ Archive not produced at $ARCHIVE_PATH"
            xcodebuild -workspace "$WORKSPACE" -list || true
            xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -showBuildSettings | \
              grep -E 'PRODUCT_NAME|PRODUCT_BUNDLE_IDENTIFIER|CODE_SIGN|DEVELOPMENT_TEAM|PROVISIONING_PROFILE|MARKETING_VERSION|CURRENT_PROJECT_VERSION' || true
            exit 1
          fi
          echo "✅ Archive created: $ARCHIVE_PATH"

      # 5) Export IPA
      - name: Export IPA
        script: |
          set -euo pipefail
          mkdir -p "$EXPORT_DIR"
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist "$EXPORT_PLIST" \
            -exportPath "$EXPORT_DIR"

          echo "Artifacts in $EXPORT_DIR:"
          ls -la "$EXPORT_DIR"

    artifacts:
      - Export/*.ipa
      - Export/*.dSYM.zip
      - ExportOptions.plist

    publishing:
      app_store_connect:
        auth: integration       # uses integrations.app_store_connect: FireCalc
        submit_to_testflight: true
