workflows:
  ios_release:
    name: iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60

    integrations:
      app_store_connect: FireCalc

    environment:
      xcode: 16.4
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.fireopscalc.app

    scripts:
      - name: Install pods
        script: |
          cd ios
          pod install --repo-update || pod install
      - name: Apply signing settings
        script: xcode-project use-profiles
      - name: Build archive
        script: |
          xcodebuild -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $CM_BUILD_DIR/build/App.xcarchive archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/build/App.xcarchive \
            -exportOptionsPlist $CM_EXPORT_OPTIONS \
            -exportPath $CM_BUILD_DIR/Export

    artifacts:
      - Export/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
