workflows:
  ios_release:
    name: FireOpsCalc iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: 16.4
      cocoapods: default
      node: 20.11.1
      # --- App identity ---
      vars:
        PRODUCT_BUNDLE_IDENTIFIER: "com.fireopscalc.app"
        DEVELOPMENT_TEAM: "QZ55W58398"
        WORKSPACE: "ios/App/App.xcworkspace"
        SCHEME: "App"
        ARCHIVE_PATH: "/Users/builder/clone/build/App.xcarchive"
        EXPORT_PATH: "/Users/builder/clone/Export"

    cache:
      cache_paths:
        - ~/Library/Caches/CocoaPods

    scripts:
      - name: Show Xcode schemes (and install Pods if present)
        script: |
          set -e
          if [ -d "ios/App" ]; then
            (cd ios/App && pod install || true)
          fi
          xcodebuild -list -workspace "$WORKSPACE" || true

      - name: (Optional) Sync Capacitor iOS
        script: |
          set -e
          if [ -f package.json ]; then
            npm ci || true
            npx cap sync ios || true
          fi

      - name: Prepare code signing (uses ASC environment variables)
        script: |
          set -e
          keychain initialize
          : "${APP_STORE_CONNECT_ISSUER_ID:?Missing APP_STORE_CONNECT_ISSUER_ID}"
          : "${APP_STORE_CONNECT_KEY_IDENTIFIER:?Missing APP_STORE_CONNECT_KEY_IDENTIFIER}"
          : "${APP_STORE_CONNECT_PRIVATE_KEY:?Missing APP_STORE_CONNECT_PRIVATE_KEY}"
          app-store-connect fetch-signing-files "$PRODUCT_BUNDLE_IDENTIFIER" \
            --type IOS_APP_STORE \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --create
          keychain add-certificates
          echo "📄 Provisioning profiles:"
          ls -lah "$HOME/Library/MobileDevice/Provisioning Profiles" || true

      - name: Build Xcode archive (Manual Distribution signing)
        script: |
          set -e
          xcodebuild -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            -destination generic/platform=iOS \
            clean archive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$PRODUCT_BUNDLE_IDENTIFIER" \
            CODE_SIGN_STYLE=Manual \
            "CODE_SIGN_IDENTITY=Apple Distribution" \
            OTHER_CODE_SIGN_FLAGS="--keychain $(security default-keychain | tr -d '\"')"

      - name: Export IPA
        script: |
          set -e
          mkdir -p "$EXPORT_PATH"
          cat > export_options.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>uploadBitcode</key><false/>
            <key>compileBitcode</key><false/>
            <key>stripSwiftSymbols</key><true/>
            <key>destination</key><string>export</string>
          </dict>
          </plist>
          EOF
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist export_options.plist \
            -exportPath "$EXPORT_PATH"
          echo "📦 Export contents:"
          ls -lah "$EXPORT_PATH"

      - name: Publish to TestFlight
        script: |
          set -e
          IPA_PATH=$(find "$EXPORT_PATH" -name "*.ipa" | head -n 1 || true)
          if [ -z "$IPA_PATH" ]; then
            echo "❌ No IPA found to publish"; exit 1; fi
          app-store-connect publish \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY" \
            --file "$IPA_PATH" \
            --submit-for-beta-review
          echo "✅ Uploaded $IPA_PATH to TestFlight"

    artifacts:
      - build/**/*
      - Export/**/*
      - export_options.plist
