workflows:
  ios_release:
    name: FireOpsCalc iOS Release
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      # Enable this variable group in Codemagic (secure values):
      #  - APP_STORE_CONNECT_PRIVATE_KEY  (full .p8 incl. BEGIN/END)
      #  - APP_STORE_CONNECT_KEY_IDENTIFIER
      #  - APP_STORE_CONNECT_ISSUER_ID
      groups:
        - appstore_connect
      xcode: 16.4
      cocoapods: default
      node: 20.11.1
      vars:
        PRODUCT_BUNDLE_IDENTIFIER: "com.fireopscalc.app"
        DEVELOPMENT_TEAM: "QZ55W58398"
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"
        ARCHIVE_PATH: "$CM_BUILD_DIR/build/App.xcarchive"
        IPA_EXPORT_DIR: "$CM_BUILD_DIR/Export"
        IPA_NAME: "FireOpsCalc.ipa"

    triggering:
      events: [push, tag]
      branch_patterns:
        - pattern: main
          include: true
          source: true

    scripts:
      - name: Install JS deps & sync Capacitor
        script: |
          if [ -f package.json ]; then
            npm ci || npm install
          fi
          npx cap sync ios || true

      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install --repo-update
          cd -

      - name: Fetch signing assets
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$PRODUCT_BUNDLE_IDENTIFIER" --type IOS_APP_STORE --create || true
          keychain add-certificates || true

      # Build UNSIGNED to avoid Pod provisioning conflicts.
      - name: Build Xcode archive (unsigned)
        script: |
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -archivePath "$ARCHIVE_PATH" \
            -destination 'generic/platform=iOS' \
            clean archive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            PRODUCT_BUNDLE_IDENTIFIER="$PRODUCT_BUNDLE_IDENTIFIER" \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO

      - name: Create exportOptions.plist (App Store, automatic)
        script: |
          cat > exportOptions.plist <<'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>automatic</string>
            <key>destination</key><string>export</string>
            <key>uploadSymbols</key><true/>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          EOF

      # Sign during export; force-find/move the IPA so Publishing can see it.
      - name: Export IPA (sign & verify)
        script: |
          set -euo pipefail

          mkdir -p "$IPA_EXPORT_DIR"
          echo "📦 Exporting archive to $IPA_EXPORT_DIR ..."
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportPath "$IPA_EXPORT_DIR" \
            -exportOptionsPlist exportOptions.plist \
            -allowProvisioningUpdates

          echo "🔍 After export, export dir contains:"
          ls -la "$IPA_EXPORT_DIR" || true

          # 1) If an IPA is already in the export dir, normalize its name.
          if compgen -G "$IPA_EXPORT_DIR/*.ipa" > /dev/null; then
            FOUND_IPA=$(ls "$IPA_EXPORT_DIR"/*.ipa | head -n 1)
            echo "✅ Found IPA in export dir: $FOUND_IPA"
            mv "$FOUND_IPA" "$IPA_EXPORT_DIR/$IPA_NAME"
          else
            # 2) Fallback: search the whole workspace for any IPA produced.
            echo "⚠️  No IPA in export dir. Searching entire workspace for *.ipa ..."
            FOUND_IPA=$(find "$CM_BUILD_DIR" -type f -name "*.ipa" | head -n 1 || true)
            if [ -n "$FOUND_IPA" ]; then
              echo "✅ Found IPA elsewhere: $FOUND_IPA"
              mv "$FOUND_IPA" "$IPA_EXPORT_DIR/$IPA_NAME"
            else
              echo "❌ No IPA found anywhere. Dumping export logs for clues:"
              LOG_CANDIDATE="$IPA_EXPORT_DIR/Packaging.log"
              [ -f "$LOG_CANDIDATE" ] && cat "$LOG_CANDIDATE" || true
              exit 2
            fi
          fi

          echo "🎯 Final IPA path: $IPA_EXPORT_DIR/$IPA_NAME"
          ls -la "$IPA_EXPORT_DIR"

    artifacts:
      - "$IPA_EXPORT_DIR/*.ipa"
      - "$ARCHIVE_PATH"
      - "exportOptions.plist"
      - "**/dSYMs/**"

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
