workflows:
  ios_release:
    name: iOS Release Build & Upload
    instance_type: mac_mini_m2
    max_build_duration: 60

    integrations:
      app_store_connect: FireCalc   # Codemagic ASC integration name

    environment:
      xcode: 16.4
      ios_signing:
        certificates:
          - FireCalcCertiicate      # EXACT reference from Codemagic (one 't', two 'i')
        provisioning_profiles:
          - FireOpsCalcprofile      # EXACT reference from Codemagic
      vars:
        DEVELOPMENT_TEAM: QZ55W58398
        EXPECTED_BUNDLE_ID: com.fireopscalc.app
        XCODE_WORKSPACE: ios/App/App.xcworkspace
        XCODE_SCHEME: App
        ARCHIVE_PATH: $CM_BUILD_DIR/build/App.xcarchive
        EXPORT_PATH: $CM_BUILD_DIR/Export

    cache:
      cache_paths:
        - ~/.npm
        - ios/Pods -> ios/Podfile.lock
        - ios/App/Pods -> ios/App/Podfile.lock

    scripts:
      - name: Install Node dependencies
        script: |
          npm ci || npm install

      - name: Capacitor sync (ensure bundle id flows into Xcode)
        script: |
          # Repo should have:
          #   ios/App/capacitor.config.json -> "appId": "com.fireopscalc.app"
          #   ios/App/config.xml            -> <widget id="com.fireopscalc.app" ...>
          npx cap sync ios
          cat ios/App/capacitor.config.json || true

      - name: Install CocoaPods (if present)
        script: |
          if [ -f "ios/App/Podfile" ]; then
            cd ios/App && pod install
          elif [ -f "ios/Podfile" ]; then
            cd ios && pod install
          else
            echo "No Podfile found (ok if not using Pods)"
          fi

      - name: Install referenced signing assets (certificate + profile)
        script: |
          xcode-project use-profiles
          echo "Profiles installed:"
          ls -l "$HOME/Library/MobileDevice/Provisioning Profiles" || true

      - name: Build archive (manual signing)
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -archivePath "$ARCHIVE_PATH" \
            archive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PRODUCT_BUNDLE_IDENTIFIER="$EXPECTED_BUNDLE_ID" \
            CODE_SIGNING_ALLOWED=YES | xcpretty

      - name: Validate archive signing
        script: |
          APP="$ARCHIVE_PATH/Products/Applications/App.app"
          INFO_PLIST="$APP/Info.plist"
          if [ ! -f "$INFO_PLIST" ]; then
            echo "Missing $INFO_PLIST"; ls -R "$ARCHIVE_PATH"; exit 1
          fi
          BUNDLE=$(/usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" "$INFO_PLIST" 2>/dev/null || true)
          echo "Archived CFBundleIdentifier: $BUNDLE"
          [ "$BUNDLE" = "$EXPECTED_BUNDLE_ID" ] || { echo "Bundle id mismatch"; exit 1; }

          if [ ! -f "$APP/embedded.mobileprovision" ]; then
            echo "❌ Missing embedded.mobileprovision (profile not embedded)"; exit 1
          fi

          security cms -D -i "$APP/embedded.mobileprovision" > /tmp/prov.plist
          echo "✅ Embedded profile name:"
          /usr/libexec/PlistBuddy -c "Print :Name" /tmp/prov.plist || true
          echo "✅ Embedded profile UUID:"
          /usr/libexec/PlistBuddy -c "Print :UUID" /tmp/prov.plist || true
          echo "✅ Embedded application-identifier:"
          /usr/libexec/PlistBuddy -c "Print :Entitlements:application-identifier" /tmp/prov.plist || true

      - name: Create ExportOptions.plist (no provisioningProfiles map)
        script: |
          cat <<EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key><string>app-store-connect</string>
            <key>teamID</key><string>$DEVELOPMENT_TEAM</string>
            <key>stripSwiftSymbols</key><true/>
            <key>uploadSymbols</key><true/>
            <key>manageAppVersionAndBuildNumber</key><false/>
            <key>compileBitcode</key><false/>
          </dict>
          </plist>
          EOF
          cat ExportOptions.plist

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath "$EXPORT_PATH" | xcpretty

    artifacts:
      - Export/*.ipa
      - $CM_BUILD_DIR/build/*.xcarchive

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
