    environment:
      node: 18
      xcode: latest
      cocoapods: default
      vars:
        APP_IDENTIFIER: com.fireopscalc.app
        APP_NAME: FireOps Calc

        # Map env vars from Codemagic UI
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY   # <-- Key ID
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSU      # <-- Issuer ID
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIV    # <-- .p8 contents

    publishing:
      app_store_connect:
        api_key_id: $APP_STORE_CONNECT_KEY        # Key ID
        issuer_id: $APP_STORE_CONNECT_ISSU        # Issuer ID
        private_key: $APP_STORE_CONNECT_PRIV      # Private key
